// Commercial lines: insurance for a business. Same fields as personal policies.

const BASICS = 'Most businesses start here';
const PEOPLE = 'Employees and management';
const THINGS = 'Vehicles, tools and data';
const WORK = 'Your professional work';

export const business = [
  {
    slug: 'bop',
    line: 'business',
    group: BASICS,
    name: 'Business owner\'s policy',
    short: 'BOP',
    codes: 'BOP',
    teaser: 'A starter package: property, liability and lost income.',
    keywords: ['small business', 'package', 'shop', 'office', 'retail', 'restaurant', 'bop'],
    lead: 'A package for small businesses that combines [property](/business/commercial-property/), [general liability](/business/general-liability/) and [business income](/business/business-income/) insurance in one policy, usually for less than buying them separately.',
    forWho: 'Small, lower-risk businesses such as shops, offices, cafés and consultancies. Insurers set limits on size and revenue, and some trades don\'t qualify.',
    required: 'Not by law, but landlords, lenders and clients often require the liability part.',
    covered: [
      'Your building if you own it, and your equipment, furniture and stock',
      'Claims that your business injured someone or damaged their property',
      'Lost income and ongoing bills while you\'re closed after covered damage',
      'Advertising injury, like accidentally using someone\'s photo in an ad',
    ],
    notCovered: [
      'Employee injuries, which need [workers\' comp](/business/workers-comp/)',
      'Mistakes in professional advice, which need [professional liability](/business/professional-liability/)',
      'Vehicles, which need [commercial auto](/business/commercial-auto/)',
      'Data breaches, which need [cyber insurance](/business/cyber/)',
      'Flood and earthquake',
      'Employment claims like wrongful firing, which need [[epli|EPLI]]',
    ],
    examples: [
      { s: 'A customer slips on a wet floor in your shop.', v: 'yes', a: 'The general liability part pays their medical bills and any claim, plus your defense.' },
      { s: 'A fire closes your café for six weeks.', v: 'yes', a: 'The property part pays for repairs and equipment; business income pays the profit you lose and ongoing bills like rent and payroll.' },
      { s: 'Your employee cuts a hand badly in the kitchen.', v: 'no', a: 'Injuries to employees aren\'t covered by a BOP. That\'s workers\' comp, which most states require once you have employees.' },
    ],
    check: ['Property limits for equipment and stock', 'Business income: how many months and how much', 'Liability limits your lease or contracts require', 'Add-ons you may need, like equipment breakdown or spoilage'],
    related: ['general-liability', 'commercial-property', 'business-income', 'workers-comp'],
  },

  {
    slug: 'general-liability',
    line: 'business',
    group: BASICS,
    name: 'General liability',
    short: 'General liability',
    codes: 'CGL',
    teaser: 'Claims that your business hurt someone or damaged their things.',
    keywords: ['cgl', 'slip and fall', 'customer injury', 'contractor', 'certificate', 'coi', 'additional insured', 'advertising injury'],
    lead: 'Covers your business when someone outside it claims you injured them, damaged their property, or harmed them through your advertising, and pays for your legal defense.',
    forWho: 'Nearly every business that deals with customers, visitors or clients\' property. Clients and landlords often ask for proof, a [[coi|certificate of insurance]].',
    required: 'Not by law, but commonly required by leases, client contracts and licensing for trades.',
    covered: [
      'Injuries to customers, visitors and the public caused by your premises or work',
      'Damage to other people\'s property',
      'Harm from something you sold or work you finished, after you\'ve finished it',
      'Libel, slander and copying someone\'s advertising idea',
      'Your legal defense, usually on top of the limit',
    ],
    notCovered: [
      'Injuries to your own employees ([workers\' comp](/business/workers-comp/))',
      'Your own property ([commercial property](/business/commercial-property/))',
      'Mistakes in professional advice or services ([professional liability](/business/professional-liability/))',
      'Car accidents ([commercial auto](/business/commercial-auto/))',
      'Redoing your own faulty work',
      'Pollution, data breaches and employment claims',
    ],
    examples: [
      { s: 'A plumber\'s fitting fails a week after the job and floods the client\'s house.', v: 'yes', a: 'Damage from finished work is covered under [[products-completed|products and completed operations]]. The cost of replacing the faulty fitting itself usually isn\'t.' },
      { s: 'A competitor says your ad copied their slogan.', v: 'yes', a: 'Advertising injury (Coverage B) usually covers this, including your defense.' },
      { s: 'A consultant\'s advice costs a client $200,000.', v: 'no', a: 'Financial harm from advice isn\'t bodily injury or property damage, so general liability doesn\'t apply. That\'s [professional liability](/business/professional-liability/).' },
    ],
    partsTitle: 'The parts of a general liability policy',
    parts: [
      { code: 'A', name: 'Bodily injury and property damage', short: 'Harm to people and things', more: ['The main part: someone hurt, or someone\'s property damaged, because of your business. Includes [[products-completed|products and completed operations]].'] },
      { code: 'B', name: 'Personal and advertising injury', short: 'Harm through words and ads', more: ['Libel, slander, invasion of privacy, false arrest, and using someone\'s advertising idea or copyright in your ads.'] },
      { code: 'C', name: 'Medical payments', short: 'Small medical bills, no-fault', more: ['Pays a visitor\'s minor medical bills without anyone needing to prove fault, which often heads off a lawsuit.'] },
    ],
    more: [
      { title: 'Limits: "$1M / $2M"', body: ['General liability usually has a [[per-occurrence]] limit and an [[aggregate]] limit, like $1 million per occurrence and $2 million per year. Contracts often specify both.'] },
      { title: 'Adding clients as "additional insured"', body: ['Clients may ask to be named an [[additional-insured]], so your policy also defends them if your work leads to a claim against them. It\'s common and usually done with an endorsement.'] },
    ],
    check: ['Per-occurrence and aggregate limits', 'Whether it\'s an [[occurrence]] policy', 'Which work is excluded for your trade', 'How to add an additional insured'],
    related: ['bop', 'professional-liability', 'commercial-umbrella', 'workers-comp'],
  },

  {
    slug: 'commercial-property',
    line: 'business',
    group: BASICS,
    name: 'Commercial property',
    short: 'Property',
    codes: 'CP, causes of loss forms',
    teaser: 'Your building, equipment and stock.',
    keywords: ['building', 'equipment', 'inventory', 'stock', 'bpp', 'coinsurance', 'fire'],
    lead: 'Pays to repair or replace your business\'s building, equipment, furniture and stock after damage from a covered cause, like fire, storm or theft.',
    forWho: 'Businesses that own a building, or have equipment, furniture or stock worth protecting, including tenants who made improvements.',
    required: 'Not by law. Lenders require it on buildings, and leases often require tenants to insure their improvements.',
    covered: [
      'The building, if you own it or your lease makes you responsible',
      'Business personal property: equipment, furniture, computers, stock',
      'Improvements you made as a tenant',
      'Other people\'s property in your care, up to a limit',
    ],
    notCovered: [
      'Flood and earthquake',
      'Equipment breakdown, like a failed compressor, unless you add it',
      'Spoiled food from a power outage, unless you add spoilage coverage',
      'Money and securities, which need a crime policy',
      'Wear and tear',
      'Property that\'s often away from your premises, which needs [inland marine](/business/inland-marine/)',
    ],
    examples: [
      { s: 'A break-in: laptops and stock are stolen.', v: 'yes', a: 'Theft of business property is covered under the "special" causes-of-loss form, minus your deductible.' },
      { s: 'A power cut spoils $8,000 of food in a restaurant\'s freezer.', v: 'depends', a: 'Only if you added spoilage coverage. If a covered storm damaged your own power line, some policies pay.' },
    ],
    partsTitle: 'Causes of loss: basic, broad, special',
    partsIntro: 'Like home policies, business property policies either list the causes they cover ([[named-perils]]) or cover all causes not excluded ([[open-perils]]).',
    parts: [
      { code: 'Basic', name: 'Basic form', short: 'A short list of causes', more: ['Fire, lightning, explosion, wind, hail, smoke, aircraft, vehicles, riot, vandalism, sprinkler leakage, sinkhole collapse and volcanic action.'] },
      { code: 'Broad', name: 'Broad form', short: 'Adds a few more', more: ['Adds falling objects, weight of snow or ice, water damage from broken systems, and some collapse.'] },
      { code: 'Special', name: 'Special form', short: 'Any cause not excluded', more: ['The broadest, and the most common for small businesses. Includes theft.'] },
    ],
    more: [
      { title: 'The coinsurance trap', body: ['Most policies have an 80% [[coinsurance-property|coinsurance]] clause: if you insure the property for less than 80% of its value, even partial claims are cut in proportion. Keep limits up to date as prices rise.'] },
    ],
    check: ['The causes-of-loss form', 'Limits for building and contents, compared with today\'s values', 'Coinsurance percentage', '[[replacement-cost]] or [[acv|actual cash value]]', 'Add-ons: equipment breakdown, spoilage, signs'],
    related: ['bop', 'business-income', 'inland-marine', 'flood'],
  },

  {
    slug: 'business-income',
    line: 'business',
    group: BASICS,
    name: 'Business income insurance',
    short: 'Business income',
    codes: 'Business interruption',
    teaser: 'Lost income while you\'re closed after damage.',
    keywords: ['business interruption', 'lost income', 'closed', 'extra expense', 'civil authority'],
    lead: 'Pays the profit you lose and the bills you still have, like rent and payroll, while your business is closed or slowed down by covered physical damage.',
    forWho: 'Any business that would struggle to pay its bills during a closure after a fire or storm.',
    required: 'No.',
    covered: [
      'Lost net income during the repair period',
      'Ongoing expenses like rent, loan payments and payroll',
      '[[extra-expense|Extra expenses]] to keep operating, like a temporary location',
      'Losses when authorities block access to your premises because of nearby damage',
    ],
    notCovered: [
      'Closures without physical damage to property, such as most pandemic closures',
      'The first 72 hours in many policies, the [[waiting-period]]',
      'Closures caused by excluded causes, like flood if you have no flood cover',
      'Losses from a supplier\'s closure, unless you add dependent property coverage',
    ],
    examples: [
      { s: 'A fire closes your bakery for two months.', v: 'yes', a: 'Pays your expected profit and continuing bills for those two months, after the waiting period.' },
      { s: 'A state order closes your business during an epidemic.', v: 'no', a: 'Business income requires direct physical damage to property. Most courts found that closures without physical damage weren\'t covered.' },
    ],
    check: ['The limit, or the number of months covered', 'The waiting period', 'Civil authority and dependent property coverage', 'Extended period after reopening while customers return'],
    related: ['bop', 'commercial-property'],
  },

  {
    slug: 'workers-comp',
    line: 'business',
    group: PEOPLE,
    name: 'Workers\' compensation',
    short: 'Workers\' comp',
    codes: 'WC / EL',
    teaser: 'Employees hurt or made ill by their job.',
    keywords: ['employees', 'work injury', 'workplace', 'staff', 'hiring', 'payroll', 'wc'],
    lead: 'Pays medical bills and part of lost wages for employees hurt or made ill by their job, whoever was at fault. In return, employees generally can\'t sue you over it.',
    forWho: 'Any business with employees. In some states even one part-time employee counts.',
    required: 'Yes, in nearly every state once you have employees. Thresholds vary; Texas is the main state where it\'s optional for private employers. In Ohio, North Dakota, Washington and Wyoming you must buy it from the state fund.',
    covered: [
      'Medical care for work-related injuries and illnesses',
      'Part of lost wages, often about two thirds',
      'Rehabilitation and retraining',
      'Death benefits for the family',
      'Lawsuits connected to work injuries, through [[employers-liability|employer\'s liability]]',
    ],
    notCovered: [
      'Independent contractors, but misclassifying an employee as a contractor can leave you liable',
      'Injuries while commuting to and from work',
      'Injuries from intoxication or horseplay, in many states',
      'Injuries outside work, which may fall under [disability](/personal/disability/) or health insurance',
    ],
    examples: [
      { s: 'A warehouse worker hurts their back lifting boxes.', v: 'yes', a: 'Medical bills and part of their wages while they recover are paid, regardless of fault.' },
      { s: 'An employee is injured in a car crash on the way to the office.', v: 'no', a: 'Ordinary commuting usually isn\'t covered. Driving between client sites during the workday usually is.' },
    ],
    partsTitle: 'The two parts',
    parts: [
      { code: '1', name: 'Workers\' compensation', short: 'Benefits set by state law', more: ['Pays what your state\'s law requires: medical care and wage benefits. There\'s no dollar limit; the law sets the benefits.'] },
      { code: '2', name: 'Employer\'s liability', short: 'Lawsuits connected to work injuries', more: ['Covers the lawsuits workers\' comp doesn\'t block, like a family member suing, up to a limit such as $100,000 or $1 million.'] },
    ],
    more: [{ title: 'How the price is worked out', body: ['Premium is based on payroll, per $100, and a rate for each type of job (class code). At the end of the year the insurer audits your real payroll and adjusts the bill.'] }],
    check: ['Every state where you have employees is listed', 'Correct job class codes', 'Whether owners are included or excluded', 'Employer\'s liability limits'],
    related: ['bop', 'management-liability', 'disability'],
  },

  {
    slug: 'management-liability',
    line: 'business',
    group: PEOPLE,
    name: 'Employment and management liability',
    short: 'EPLI and D&O',
    codes: 'EPLI, D&O, fiduciary',
    teaser: 'Claims from employees, and against leaders.',
    keywords: ['epli', 'd&o', 'directors', 'officers', 'harassment', 'discrimination', 'wrongful termination', 'board', 'nonprofit'],
    lead: 'Covers claims that aren\'t about physical injury: an employee alleging discrimination or wrongful firing ([[epli|EPLI]]), or someone suing the people who run the company over their decisions ([[do|D&O]]).',
    forWho: 'EPLI: any business with employees. D&O: companies with investors or a board, and nonprofits with volunteer boards.',
    required: 'No, but investors and board members often expect D&O.',
    covered: [
      'Claims of wrongful termination, discrimination, harassment and retaliation (EPLI)',
      'Claims that leaders mismanaged the company, breached duties or misled investors (D&O)',
      'Legal defense, which is often the biggest cost',
      'Settlements and judgments, up to the limit',
    ],
    notCovered: [
      'Unpaid wages and overtime claims, except sometimes defense costs',
      'Fraud or crimes that are proven',
      'Bodily injury and property damage',
      'Claims known before the policy started',
    ],
    examples: [
      { s: 'A fired employee claims age discrimination.', v: 'yes', a: 'EPLI pays your defense and any settlement, above its [[deductible|retention]]. General liability wouldn\'t.' },
      { s: 'Investors sue the board over a failed acquisition.', v: 'yes', a: 'D&O pays defense and settlements for the directors and officers, and often the company.' },
    ],
    more: [{ title: 'Claims-made policies', body: ['These policies are [[claims-made]]: the claim has to be made while the policy is active. If you cancel or close the business, ask about [[tail]] coverage.'] }],
    check: ['Retention (deductible)', 'Whether defense costs reduce the limit', 'Retroactive date', 'Third-party coverage, for claims from customers'],
    related: ['workers-comp', 'professional-liability', 'cyber'],
  },

  {
    slug: 'commercial-auto',
    line: 'business',
    group: THINGS,
    name: 'Commercial auto',
    short: 'Commercial auto',
    codes: 'Business auto, HNOA',
    teaser: 'Vehicles used for business.',
    keywords: ['van', 'truck', 'fleet', 'business vehicle', 'hnoa', 'delivery', 'employee driving'],
    lead: 'Covers vehicles your business owns or uses: liability for crashes and, if chosen, damage to the vehicles. It works like [car insurance](/personal/auto/) with business uses allowed.',
    forWho: 'Businesses with vans, trucks or cars, or whose employees drive for work.',
    required: 'Yes, for business-owned vehicles, at least the state\'s minimum liability. Trucking and passenger transport have federal requirements.',
    covered: ['Injuries and damage your business vehicles cause', 'Damage to the vehicles, with collision and comprehensive', 'Employees driving business vehicles', 'Rented or personal cars used for work, with [[hnoa|hired and non-owned auto]]'],
    notCovered: ['Tools and equipment in the van, which need [inland marine](/business/inland-marine/)', 'Employee injuries, which [workers\' comp](/business/workers-comp/) covers', 'Mechanical breakdown'],
    examples: [
      { s: 'An employee crashes the company van on the way to a job.', v: 'yes', a: 'Commercial auto pays the other party\'s damages and, with collision, the van. The employee\'s injuries go to workers\' comp.' },
      { s: 'An employee runs a work errand in their own car and causes a crash.', v: 'depends', a: 'The employee\'s own policy pays first. [[hnoa|Hired and non-owned auto]] protects your business if it\'s sued too.' },
    ],
    check: ['Every vehicle and driver listed', 'Hired and non-owned auto included', 'Liability limits your contracts require'],
    related: ['auto', 'workers-comp', 'inland-marine'],
  },

  {
    slug: 'inland-marine',
    line: 'business',
    group: THINGS,
    name: 'Tools, equipment and goods in transit',
    short: 'Inland marine',
    codes: 'Inland marine',
    teaser: 'Business property that moves around.',
    keywords: ['tools', 'equipment', 'contractor', 'photographer', 'transit', 'floater', 'job site'],
    lead: 'Despite the name, covers business property that moves: a contractor\'s tools, a photographer\'s cameras, materials on a job site, goods on a truck.',
    forWho: 'Contractors, tradespeople, event businesses, and anyone whose equipment travels.',
    required: 'No.',
    covered: ['Tools and equipment at job sites and in vehicles', 'Materials being installed, until the job is finished', 'Goods in transit', 'Valuable papers and records'],
    notCovered: ['Wear and tear, and breakdown', 'Theft from an unlocked, unattended vehicle, in many policies', 'Property that never leaves your premises, which [commercial property](/business/commercial-property/) covers'],
    examples: [{ s: 'Tools are stolen from a locked van overnight.', v: 'yes', a: 'A contractor\'s equipment policy usually pays. Check for night-time or visible-entry conditions.' }],
    check: ['A list of scheduled equipment with values', 'Theft conditions', 'Coverage for rented or borrowed equipment'],
    related: ['commercial-property', 'commercial-auto', 'general-liability'],
  },

  {
    slug: 'cyber',
    line: 'business',
    group: THINGS,
    name: 'Cyber insurance',
    short: 'Cyber',
    codes: 'Cyber liability',
    teaser: 'Data breaches, ransomware and online fraud.',
    keywords: ['data breach', 'hack', 'ransomware', 'phishing', 'privacy', 'computer', 'fraud', 'wire transfer'],
    lead: 'Pays the costs of a data breach or cyberattack: investigation, notifying customers, restoring systems, lost income, and claims from people whose data was exposed.',
    forWho: 'Any business that stores customer data, takes payments, or can\'t operate without its computers.',
    required: 'No, but some clients and contracts require it.',
    covered: [
      'Forensic investigation and legal advice after a breach',
      'Notifying affected customers and credit monitoring',
      'Ransomware response and restoring data',
      'Lost income while systems are down',
      'Lawsuits and some regulatory fines from exposed data',
    ],
    notCovered: [
      'Money sent to a scammer after a fake invoice or email, unless you added social engineering coverage',
      'Improving your security after an attack',
      'Losses from known, unfixed security problems',
      'Damage to physical equipment',
    ],
    examples: [
      { s: 'Ransomware locks your systems for a week.', v: 'yes', a: 'Pays experts to respond and restore, lost income during the outage, and in many policies, a ransom payment where lawful.' },
      { s: 'Your bookkeeper wires $40,000 to a fake supplier after a convincing email.', v: 'depends', a: 'Only covered if you added social engineering (or funds transfer fraud) coverage, often with a low limit.' },
    ],
    check: ['Social engineering coverage and its limit', 'Security requirements like multi-factor authentication', 'A 24/7 breach hotline', 'Business interruption waiting period'],
    related: ['professional-liability', 'management-liability'],
  },

  {
    slug: 'professional-liability',
    line: 'business',
    group: WORK,
    name: 'Professional liability',
    short: 'E&O',
    codes: 'E&O, malpractice',
    teaser: 'Claims that your advice or service caused a client a loss.',
    keywords: ['errors and omissions', 'e&o', 'malpractice', 'consultant', 'advice', 'negligence', 'freelancer', 'accountant', 'architect'],
    lead: 'Covers claims that your professional advice or service was wrong, late or negligent, and cost a client money. Also called errors and omissions (E&O) or, for doctors and lawyers, malpractice.',
    forWho: 'Consultants, designers, developers, accountants, agents, architects, and anyone paid for expertise.',
    required: 'Required for some licensed professions, and by many client contracts.',
    covered: ['Claims of negligence, mistakes or missed deadlines', 'Claims that you failed to deliver what you promised', 'Your legal defense, even if the claim is groundless'],
    notCovered: ['Bodily injury and property damage, which [general liability](/business/general-liability/) covers', 'Intentional wrongdoing and fraud', 'Claims made after the policy ends, without [[tail]] coverage', 'Refunds of your own fees, in many policies'],
    examples: [
      { s: 'A bug in software you built causes a client\'s checkout to fail for three days.', v: 'yes', a: 'The client\'s lost sales claim is covered, including your defense.' },
      { s: 'You stopped your policy last year, and a client sues now over work from two years ago.', v: 'no', a: 'These are [[claims-made]] policies: the policy must be active when the claim arrives, unless you bought [[tail]] coverage.' },
    ],
    check: ['Retroactive date', 'What services the policy describes: it should match what you actually do', 'Whether defense costs reduce the limit'],
    related: ['general-liability', 'cyber', 'management-liability'],
  },

  {
    slug: 'commercial-umbrella',
    line: 'business',
    group: WORK,
    name: 'Commercial umbrella',
    short: 'Umbrella',
    codes: 'Umbrella, excess',
    teaser: 'Extra liability on top of your business policies.',
    keywords: ['excess', 'umbrella', 'contract requirement'],
    lead: 'Adds liability protection above your general liability, commercial auto and employer\'s liability limits, for large claims.',
    forWho: 'Businesses with contracts that require higher limits, vehicles on the road, or heavy public exposure.',
    required: 'No, but contracts often require $1 million to $5 million in total.',
    covered: ['Claims above the limits of your underlying policies', 'Defense costs'],
    notCovered: ['Most things the underlying policies exclude (some umbrellas cover a few, above a self-insured retention)', 'Professional liability, cyber and management claims'],
    examples: [{ s: 'A delivery van crash causes a $2 million judgment; your auto limit is $1 million.', v: 'yes', a: 'The umbrella pays the second million, up to its limit.' }],
    check: ['Which underlying policies it sits over', 'Required underlying limits'],
    related: ['general-liability', 'commercial-auto', 'umbrella'],
  },
];
