// Glossary. `slug` is what content uses in [[slug]] links.
// Definitions: one or two plain sentences, then an optional example.

export const glossary = [
  // ---- core ideas
  { slug: 'premium', term: 'Premium', def: 'The price of the policy: what you pay the insurer, monthly or yearly, to be covered.', example: '$1,800 a year for home insurance, or $150 a month for car insurance.' },
  { slug: 'deductible', term: 'Deductible', def: 'The part of a covered loss you pay yourself before the insurer pays the rest. A higher deductible usually means a lower premium.', example: 'A storm causes $6,000 of damage and your deductible is $1,000. You pay $1,000 and the insurer pays $5,000.' },
  { slug: 'limit', term: 'Limit', def: 'The most the policy will pay. Anything above the limit is on you.', example: 'Your liability limit is $300,000 and a court awards $400,000. You owe the other $100,000.' },
  { slug: 'sublimit', term: 'Sublimit', def: 'A smaller cap inside a larger limit for a specific kind of item or loss.', example: 'Your belongings are covered up to $50,000, but stolen jewelry only up to $1,500.' },
  { slug: 'aggregate', label: 'aggregate', term: 'Aggregate limit', def: 'The most a policy will pay for all claims added together during the policy period, usually one year.', example: '$1 million per occurrence and $2 million aggregate: no single incident over $1M, and no more than $2M for the whole year.' },
  { slug: 'per-occurrence', label: 'per-occurrence', term: 'Per-occurrence limit', def: 'The most a policy will pay for one incident, no matter how many people or claims come from it.' },
  { slug: 'peril', term: 'Peril', def: 'A cause of loss, like fire, wind, theft or a burst pipe.', example: 'Lightning is a peril. The burnt roof is the damage.' },
  { slug: 'named-perils', term: 'Named perils', def: 'A way of writing a policy that covers only the causes of loss it lists. If a cause isn\'t listed, it isn\'t covered.' },
  { slug: 'open-perils', term: 'Open perils', aka: 'special form, "all risk"', def: 'A way of writing a policy that covers every cause of loss except the ones it specifically excludes. Broader than named perils.' },
  { slug: 'exclusion', term: 'Exclusion', def: 'Something the policy says it will not cover, even if it would otherwise fit.', example: 'Flood is excluded from standard home policies.' },
  { slug: 'endorsement', term: 'Endorsement', aka: 'rider', def: 'A change added to a standard policy that adds, removes or adjusts coverage. Endorsements override the main policy text.', example: 'A water backup endorsement adds cover for sewage backing up through a drain.' },
  { slug: 'declarations', label: 'declarations', term: 'Declarations page', aka: 'dec page', def: 'The summary page of your policy: who and what is insured, the coverages you bought, their limits, your deductibles, the policy period and the price.' },
  { slug: 'replacement-cost', term: 'Replacement cost', def: 'Paying what it costs to repair or replace something with new, similar quality, with no deduction for age.', example: 'Your 6-year-old TV is stolen. Replacement cost pays for a comparable new TV.' },
  { slug: 'acv', term: 'Actual cash value', aka: 'ACV', def: 'Replacement cost minus depreciation, meaning what the item was worth given its age and wear. Pays less than replacement cost.', example: 'A comparable new TV costs $900, but yours was 6 years old. ACV might pay $300.' },
  { slug: 'depreciation', term: 'Depreciation', def: 'The loss in value from age and wear. Actual cash value payouts subtract it.' },
  { slug: 'claim', term: 'Claim', def: 'Your request to the insurer to pay for a loss under your policy.' },
  { slug: 'adjuster', term: 'Adjuster', def: 'The person who investigates a claim and works out how much the insurer owes. Usually works for the insurer. A "public adjuster" works for you, for a fee.' },
  { slug: 'agent', term: 'Agent', def: 'A licensed person who sells insurance. A "captive" agent sells for one company; an "independent" agent can quote several.' },
  { slug: 'broker', term: 'Broker', def: 'A licensed intermediary who shops policies from many insurers on your behalf. Common for business insurance.' },
  { slug: 'subrogation', term: 'Subrogation', def: 'After paying you, your insurer can go after the person who caused the loss to get its money back, and often your deductible too.' },
  { slug: 'policy-period', term: 'Policy period', def: 'The dates the policy is in force, often one year for home and business, six or twelve months for car.' },
  { slug: 'waiting-period', term: 'Waiting period', def: 'Time between buying a policy and when coverage starts, or before a benefit starts paying.', example: 'Flood insurance through the NFIP usually starts 30 days after you buy it.' },
  { slug: 'liability', term: 'Liability', def: 'Your legal responsibility for harm you cause to other people or their property. Liability coverage pays their claims against you and your legal defense.' },
  { slug: 'bodily-injury', term: 'Bodily injury', def: 'Physical harm to another person, such as a broken arm. Liability coverage pays for their medical bills, lost wages and pain and suffering if you\'re responsible.' },
  { slug: 'property-damage', term: 'Property damage', def: 'Damage to someone else\'s property. In liability coverage it pays when you\'re responsible, like your car hitting their fence.' },

  // ---- home
  { slug: 'dwelling', term: 'Dwelling coverage', aka: 'Coverage A', def: 'Pays to repair or rebuild the house itself and things attached to it, like the roof, walls, built-in appliances and a garage attached to the house.' },
  { slug: 'other-structures', term: 'Other structures', aka: 'Coverage B', def: 'Covers buildings on your property that aren\'t attached to the house, like a detached garage, shed or fence. Usually 10% of the dwelling limit.' },
  { slug: 'personal-property', term: 'Personal property', aka: 'Coverage C, contents', def: 'Your belongings: furniture, clothes, electronics, kitchenware. Covered at home and usually anywhere in the world.' },
  { slug: 'loss-of-use', term: 'Loss of use', aka: 'Coverage D, additional living expenses', def: 'Pays extra living costs, like a hotel and restaurant meals above your normal grocery bill, while your home can\'t be lived in after a covered loss.' },
  { slug: 'fair-rental-value', term: 'Fair rental value', def: 'Pays a landlord the rent they lose while a rental unit can\'t be lived in after a covered loss.' },
  { slug: 'personal-liability', term: 'Personal liability', aka: 'Coverage E', def: 'Pays if you, your family or your pet injure someone or damage their property, and you\'re legally responsible. Includes your legal defense.' },
  { slug: 'medical-payments', term: 'Medical payments to others', aka: 'Coverage F, med pay', def: 'Pays small medical bills for a guest hurt on your property, no matter who was at fault. Usually $1,000 to $5,000.' },
  { slug: 'scheduled-property', term: 'Scheduled personal property', aka: 'floater', def: 'Listing a valuable item, like an engagement ring, on your policy for its appraised value. It removes the low sublimit and often covers loss, not just theft.' },
  { slug: 'water-backup', term: 'Water backup coverage', def: 'An add-on for water that backs up through sewers or drains, or overflows a sump pump. Excluded from standard home policies unless you add it.' },
  { slug: 'wind-deductible', term: 'Hurricane or wind deductible', def: 'A separate, larger deductible for wind or hurricane damage, often a percentage of your dwelling limit rather than a dollar amount.', example: 'A 2% hurricane deductible on a $400,000 house is $8,000.' },
  { slug: 'ordinance-or-law', term: 'Ordinance or law coverage', def: 'Pays the extra cost of rebuilding to current building codes after a covered loss. Standard policies include only a small amount.', example: 'Your 1970s house burns down, and code now requires sprinklers and new wiring. This pays the difference.' },
  { slug: 'nfip', term: 'NFIP', aka: 'National Flood Insurance Program', def: 'The federal program, run by FEMA (the US disaster agency), that sells most US flood insurance through regular insurance agents.' },
  { slug: 'flood-zone', term: 'Flood zone', def: 'An area mapped by FEMA, the US federal disaster agency, by how likely it is to flood. In a high-risk zone, most mortgage lenders must require flood insurance.' },
  { slug: 'mortgagee', term: 'Mortgagee', def: 'Your mortgage lender. It\'s named on your home policy so claim checks for the house include the lender.' },

  { slug: 'master-policy', term: 'Master policy', def: 'The insurance a condo or homeowners association buys for the building and shared areas. What it covers inside units varies, so owners need to know which kind it is.' },
  { slug: 'loss-assessment', label: 'loss assessment', term: 'Loss assessment', def: 'A charge an association passes on to each owner when a loss to shared property isn\'t fully paid by its insurance. Loss assessment coverage pays your share.' },

  // ---- auto
  { slug: 'collision', label: 'collision', term: 'Collision coverage', def: 'Pays to repair your own car after it hits another car or an object, or rolls over, whoever was at fault.' },
  { slug: 'comprehensive', label: 'comprehensive', term: 'Comprehensive coverage', aka: 'other than collision', def: 'Pays for damage to your car from things other than a crash: theft, hail, flood, fire, falling trees, vandalism, hitting a deer.' },
  { slug: 'uninsured-motorist', term: 'Uninsured/underinsured motorist', aka: 'UM/UIM', def: 'Pays for your injuries, and in some states your car, when the at-fault driver has no insurance or too little.' },
  { slug: 'pip', term: 'Personal injury protection', aka: 'PIP', def: 'Pays your and your passengers\' medical bills and some lost wages after a crash, no matter who was at fault. Required in no-fault states.' },
  { slug: 'no-fault', term: 'No-fault state', def: 'A state where your own insurance pays your injury costs after a crash, up to a limit, regardless of fault. You can sue the other driver only for serious injuries. About a dozen states, including Florida, New York and Michigan.' },
  { slug: 'split-limits', term: 'Split limits', def: 'Liability limits written as three numbers, in thousands: injury per person, injury per accident, property damage per accident.', example: '50/100/50 means $50,000 per injured person, $100,000 total per accident, $50,000 for property.' },
  { slug: 'gap', term: 'Gap insurance', def: 'If your car is totaled, pays the difference between what the car is worth and what you still owe on the loan or lease.' },
  { slug: 'sr22', term: 'SR-22', def: 'A form your insurer files with the state to prove you carry insurance, often required after a serious violation like a DUI or driving uninsured.' },

  // ---- health
  { slug: 'copay', term: 'Copay', def: 'A fixed amount you pay for a specific service, like $30 for a doctor visit.' },
  { slug: 'coinsurance', label: 'coinsurance', term: 'Coinsurance (health)', def: 'Your percentage share of costs after you meet your deductible.', example: 'With 20% coinsurance, a $2,000 bill after your deductible costs you $400.' },
  { slug: 'oop-max', term: 'Out-of-pocket maximum', def: 'The most you\'ll pay for covered, in-network care in a year. After that the plan pays 100%. Premiums don\'t count toward it.' },
  { slug: 'network', term: 'Network', def: 'The doctors and hospitals that have a contract with your health plan. Going outside it costs more, or isn\'t covered at all.' },
  { slug: 'hmo', term: 'HMO', def: 'A health plan that only covers doctors in its network (except emergencies) and usually needs a referral from your primary doctor to see a specialist. Often cheaper.' },
  { slug: 'ppo', term: 'PPO', def: 'A health plan that lets you see specialists without a referral and pays part of out-of-network care. Usually a higher premium.' },
  { slug: 'epo', term: 'EPO', def: 'A health plan like an HMO in that it doesn\'t pay out of network, but usually doesn\'t need referrals.' },
  { slug: 'hdhp', term: 'High-deductible health plan', aka: 'HDHP', def: 'A plan with a higher deductible and lower premium that lets you open a tax-free health savings account (HSA).' },
  { slug: 'hsa', term: 'HSA', aka: 'health savings account', def: 'A tax-advantaged savings account for medical costs, available only with a qualifying high-deductible plan. The money is yours to keep, even if you change jobs.' },
  { slug: 'fsa', term: 'FSA', aka: 'flexible spending account', def: 'An employer account you fund from your paycheck, tax-free, for medical costs. Unused money is generally lost at year-end, unless your employer offers a small carryover or grace period.' },
  { slug: 'open-enrollment', term: 'Open enrollment', def: 'The yearly window when you can sign up for or change health insurance. For HealthCare.gov it usually runs from November 1 to January 15.' },
  { slug: 'sep', term: 'Special enrollment period', def: 'A window, usually 60 days, to get health coverage outside open enrollment after a life event like moving to the US, losing job coverage, marriage or a baby.' },
  { slug: 'marketplace', term: 'Marketplace', aka: 'exchange, HealthCare.gov', def: 'The government-run place to compare and buy individual health plans. Depending on income you may get help paying the premium. Some states run their own site.' },
  { slug: 'cobra', term: 'COBRA', def: 'A federal rule that lets you keep your employer health plan, usually for up to 18 months, after leaving the job. You pay the full premium plus up to 2%, which is often expensive. It applies to employers with 20 or more employees.' },
  { slug: 'eob', term: 'Explanation of benefits', aka: 'EOB', def: 'A statement from your health plan showing what a provider billed, what the plan paid, and what you owe. It is not a bill.' },
  { slug: 'prior-auth', term: 'Prior authorization', def: 'Approval your health plan requires before some treatments, scans or drugs, or it may not pay.' },

  // ---- life, disability, travel
  { slug: 'beneficiary', term: 'Beneficiary', def: 'The person or people who receive the money from a life insurance policy.' },
  { slug: 'term-life', term: 'Term life insurance', def: 'Life insurance for a set number of years, like 20 or 30. Pays only if you die in that time. Much cheaper than permanent insurance.' },
  { slug: 'permanent-life', term: 'Permanent life insurance', aka: 'whole life, universal life', def: 'Life insurance meant to last your whole life that also builds a cash value. Much more expensive than term for the same payout.' },
  { slug: 'elimination-period', term: 'Elimination period', def: 'How long you must be unable to work before disability insurance starts paying, like 90 days.' },
  { slug: 'cfar', term: 'Cancel for any reason', aka: 'CFAR', def: 'A travel insurance upgrade that refunds part of your trip cost, usually 50 to 75%, if you cancel for a reason the standard policy doesn\'t list. It must be bought soon after your first trip payment.' },
  { slug: 'pre-existing', term: 'Pre-existing condition', def: 'A health problem you had before the coverage started. Travel insurance often excludes it unless you get a waiver by buying early. ACA health plans can\'t exclude it.' },
  { slug: 'covered-reason', term: 'Covered reason', def: 'In travel insurance, one of the specific reasons listed in the policy that allow a refund, like your illness or a hurricane at your destination.' },

  // ---- extra liability
  { slug: 'umbrella', term: 'Umbrella policy', def: 'Extra liability coverage that starts where your home and car liability limits run out, usually in $1 million steps.' },

  // ---- business
  { slug: 'bop', term: 'Business owner\'s policy', aka: 'BOP', def: 'A package for small businesses that combines property insurance, general liability and business income coverage, usually cheaper than buying them separately.' },
  { slug: 'cgl', term: 'Commercial general liability', aka: 'CGL, general liability', def: 'Covers a business when it\'s blamed for injuring someone, damaging their property, or harming them through advertising.' },
  { slug: 'products-completed', term: 'Products and completed operations', def: 'The part of general liability that covers harm caused by something you sold or work you finished, after it left your hands.', example: 'A deck you built collapses a month after you finished it.' },
  { slug: 'occurrence', label: 'occurrence', term: 'Occurrence policy', def: 'Covers incidents that happen during the policy period, even if the claim comes years later. Most general liability works this way.' },
  { slug: 'claims-made', label: 'claims-made', term: 'Claims-made policy', def: 'Covers claims made while the policy is active, for incidents after its retroactive date. Common for professional, cyber and management liability. If you cancel, you may need "tail" coverage.' },
  { slug: 'tail', label: 'tail', term: 'Tail coverage', aka: 'extended reporting period', def: 'An add-on to a claims-made policy that lets you report claims after the policy ends, for work done while it was active.' },
  { slug: 'business-income', term: 'Business income', aka: 'business interruption', def: 'Pays the income a business loses, and ongoing bills like rent and payroll, while it\'s closed after covered physical damage.' },
  { slug: 'extra-expense', term: 'Extra expense', def: 'Pays the extra costs of keeping a business running after covered damage, like renting a temporary space.' },
  { slug: 'workers-comp', term: 'Workers\' compensation', def: 'Pays medical bills and part of lost wages for employees hurt or made ill by their job, regardless of fault. In return, employees generally can\'t sue the employer.' },
  { slug: 'employers-liability', term: 'Employer\'s liability', def: 'The second part of a workers\' comp policy. Covers lawsuits related to work injuries that fall outside workers\' comp, like a spouse suing for loss of companionship.' },
  { slug: 'additional-insured', term: 'Additional insured', def: 'Someone else added to your policy so it also protects them for claims arising from your work. Clients and landlords often require it.' },
  { slug: 'coi', term: 'Certificate of insurance', aka: 'COI', def: 'A one-page summary proving a business has insurance, often requested by clients and landlords. It doesn\'t change the coverage itself.' },
  { slug: 'hnoa', term: 'Hired and non-owned auto', aka: 'HNOA', def: 'Business liability coverage for when you or employees drive rented or personal cars for work.' },
  { slug: 'inland-marine', term: 'Inland marine', def: 'Despite the name, insurance for business property that moves around, like a contractor\'s tools, a photographer\'s gear, or goods in transit.' },
  { slug: 'coinsurance-property', term: 'Coinsurance (property)', def: 'A rule in business property policies: if you insure a building for less than a set share of its value, usually 80%, claim payments are cut in proportion.', example: 'Building worth $1M, insured for $600k with an 80% clause. You should carry $800k, so you carry 75% of the requirement, and a $100k loss pays about $75k minus the deductible.' },
  { slug: 'epli', term: 'Employment practices liability', aka: 'EPLI', def: 'Covers a business against claims from employees or applicants, like wrongful firing, discrimination or harassment.' },
  { slug: 'do', term: 'Directors and officers liability', aka: 'D&O', def: 'Covers the people running a company or nonprofit, and often the organization, against claims about their management decisions.' },
  { slug: 'eo', term: 'Professional liability', aka: 'errors and omissions, E&O, malpractice', def: 'Covers claims that your professional advice or service was wrong, late or negligent and cost a client money.' },
  { slug: 'surety-bond', term: 'Surety bond', def: 'Not insurance for you: a guarantee to your client or the state that you\'ll do what you promised. If the bond pays out, you must repay the bond company.' },
];
