// Personal lines: car, people (health, life, income), travel and extras.

export const other = [
  {
    slug: 'auto',
    line: 'personal',
    group: 'Your car',
    name: 'Car insurance',
    short: 'Car',
    codes: 'Personal auto',
    teaser: 'Harm you cause while driving, and damage to your own car.',
    keywords: ['auto', 'vehicle', 'driving', 'liability', 'collision', 'comprehensive', 'accident', 'crash', 'driver'],
    lead: 'Pays for injuries and damage you cause to others while driving, and, if you choose, for damage to your own car and your own medical bills.',
    forWho: 'Anyone who owns a car, or drives regularly.',
    required: 'Yes. Almost every state requires at least liability coverage (New Hampshire is the main exception). Some states also require [[pip|PIP]] or [[uninsured-motorist|uninsured motorist]] coverage. If you finance or lease, the lender requires [[collision]] and [[comprehensive]] too.',
    covered: [
      'Other people\'s injuries and car repairs when you\'re at fault (liability)',
      'Your own car after a crash, if you have [[collision]]',
      'Your car after theft, hail, flood, fire, vandalism or hitting a deer, if you have [[comprehensive]]',
      'Your injuries when the at-fault driver has no insurance or too little, if you have [[uninsured-motorist|uninsured motorist]] coverage',
      'Your and your passengers\' medical bills, if you have medical payments or [[pip|PIP]]',
      'Friends who borrow your car with permission, in most cases',
    ],
    notCovered: [
      'Damage to your own car if you only carry liability',
      'Mechanical breakdown, worn tires and brakes, and maintenance',
      'Belongings stolen from the car, which [home](/personal/home/) or [renters](/personal/renters/) insurance covers',
      'Driving for Uber, Lyft or deliveries, unless you add rideshare coverage',
      'Using the car mainly for a business, which needs [commercial auto](/business/commercial-auto/)',
      'Anything above your limits, which becomes your personal debt',
    ],
    examples: [
      { s: 'You rear-end another car at a red light.', v: 'depends', a: 'Your liability coverage pays for the other car and the other driver\'s injuries. Repairs to your own car are covered only if you have [[collision]].' },
      { s: 'You hit a deer on a country road.', v: 'yes', a: 'Hitting an animal falls under [[comprehensive]], not collision, if you carry it. Swerving and hitting a tree instead counts as collision.' },
      { s: 'Hail dents your car in a parking lot.', v: 'yes', a: 'Covered by [[comprehensive]], minus its deductible.' },
      { s: 'A driver with no insurance runs a red light and hits you.', v: 'yes', a: '[[uninsured-motorist|Uninsured motorist]] coverage pays your injuries, and in some states your car. Without it, you\'d have to rely on collision and health insurance, or sue the driver.' },
      { s: 'Your engine fails at 90,000 miles.', v: 'no', a: 'Breakdowns and wear aren\'t covered by standard car insurance. Some insurers sell mechanical breakdown coverage; otherwise it\'s what a warranty or service contract is for.' },
      { s: 'You crash while delivering food for an app.', v: 'depends', a: 'Personal policies usually exclude delivery and rideshare driving. The app\'s insurance may cover part of the trip. A rideshare endorsement on your own policy fills the gap.' },
    ],
    partsTitle: 'The parts of a car policy',
    partsIntro: 'Your [[declarations]] page lists each coverage separately, per car. Liability limits are written as [[split-limits]], like 50/100/50.',
    parts: [
      { code: 'BI', name: 'Bodily injury liability', short: 'Other people\'s injuries', more: ['Pays for injuries you cause others: medical bills, lost wages, pain and suffering, and your legal defense. Required almost everywhere.'], example: 'You run a stop sign and injure a cyclist.' },
      { code: 'PD', name: 'Property damage liability', short: 'Other people\'s property', more: ['Pays for other cars, fences, buildings or anything else you damage. Required almost everywhere.'] },
      { code: 'UM', name: 'Uninsured / underinsured motorist', short: 'When the other driver can\'t pay', more: ['Protects you when the at-fault driver has no insurance, too little, or drives off. About one in seven US drivers is uninsured.'] },
      { code: 'MP / PIP', name: 'Medical payments or personal injury protection', short: 'Your own medical bills', more: ['Pays medical costs for you and your passengers, whoever was at fault. [[pip|PIP]] also pays some lost wages, and is required in [[no-fault]] states.'] },
      { code: 'COLL', name: 'Collision', short: 'Your car, after a crash', more: ['Pays to repair your car after it hits a car or an object, minus your deductible, up to the car\'s value. It doesn\'t pay more than the car is worth.'] },
      { code: 'COMP', name: 'Comprehensive', short: 'Your car, everything else', more: ['Theft, fire, hail, flood, falling objects, vandalism, animals, broken glass.'] },
      { code: 'Extras', name: 'Rental, roadside, gap', short: 'Optional add-ons', more: ['Rental reimbursement pays for a rental car while yours is being repaired after a covered claim. Roadside assistance pays for towing and jump-starts. [[gap|Gap insurance]] pays off the rest of a loan if the car is totaled.'] },
    ],
    more: [
      { title: 'State minimums are low', body: ['Many state minimums, such as 25/50/25, were set decades ago. One serious injury can exceed $25,000 quickly, and you personally owe anything above your limit. Higher limits, such as 100/300/100, cost more but protect more of your savings and future income.'] },
      { title: 'Rental cars', body: ['Your US policy usually extends to a rental car you drive in the US, with the same coverages and deductibles. Many credit cards add secondary coverage for damage to the rental. Your US policy usually covers you in Canada, but not in Mexico or overseas. Mexico requires Mexican liability insurance.'] },
      { title: 'Why premiums vary so much', body: ['Price depends on your state and ZIP code, your driving record, the car, and in most states your credit history. Newcomers with no US driving record often pay much more for the first year or two.'] },
    ],
    check: [
      'Your liability limits, compared with what you own',
      'Whether you have [[collision]] and [[comprehensive]], and their deductibles',
      '[[uninsured-motorist|Uninsured motorist]] limits',
      'Every regular driver in your household is listed',
      'Whether you drive for an app or use the car for work',
    ],
    related: ['umbrella', 'commercial-auto', 'health'],
  },

  {
    slug: 'umbrella',
    line: 'personal',
    group: 'Extra protection',
    name: 'Umbrella insurance',
    short: 'Umbrella',
    codes: 'Personal umbrella',
    teaser: 'Extra liability on top of home and car.',
    keywords: ['excess liability', 'lawsuit', 'sued', 'million'],
    lead: 'Adds extra liability protection, usually $1 million or more, on top of your home and car policies, for when a serious accident or lawsuit exceeds their limits.',
    forWho: 'People with savings, a home, or future income worth protecting, and people with a pool, a teen driver, a dog or a rental property.',
    required: 'No. The insurer will require minimum liability limits on your home and car policies first.',
    covered: [
      'Injury or damage claims against you above your home or car liability limits',
      'Your legal defense costs, often on top of the limit',
      'Some claims your other policies leave out, like libel or slander',
      'You and your household, worldwide',
    ],
    notCovered: [
      'Your own injuries or your own property',
      'Business activities, which need a [commercial umbrella](/business/commercial-umbrella/)',
      'Harm you meant to cause',
      'Claims between members of your household',
    ],
    examples: [
      { s: 'You cause a crash that seriously injures two people, and the court awards $800,000.', v: 'yes', a: 'Your car policy pays up to its limits, say $300,000 in total. The umbrella pays the rest, up to its own limit. With split limits, the per-person cap can mean the car policy pays less and the umbrella more.' },
      { s: 'A guest is injured in your pool and sues.', v: 'yes', a: 'Your home policy\'s liability pays first; the umbrella pays whatever goes over its limit.' },
    ],
    more: [{ title: 'Why Americans carry so much liability coverage', body: ['US courts can award large amounts for medical costs, lost income and pain and suffering, and someone who wins a judgment can pursue your savings and future wages. An umbrella is usually an inexpensive way to raise that protection a lot.'] }],
    check: ['The minimum limits the umbrella requires on your home and car policies', 'That every car, home and rental property is listed'],
    related: ['home', 'auto', 'landlord'],
  },

  {
    slug: 'health',
    line: 'personal',
    group: 'Health, life and income',
    name: 'Health insurance',
    short: 'Health',
    codes: 'Employer, Marketplace, Medicare, Medicaid',
    teaser: 'Doctor, hospital and prescription costs.',
    keywords: ['medical', 'doctor', 'hospital', 'aca', 'obamacare', 'healthcare.gov', 'deductible', 'copay', 'dental', 'vision', 'prescription', 'emergency'],
    lead: 'Pays for doctor visits, hospital care and prescriptions. Most Americans get it through a job, the government (Medicare or Medicaid), or a plan they buy on the [[marketplace]].',
    forWho: 'Everyone. A single hospital stay in the US can cost tens of thousands of dollars.',
    required: 'No federal requirement since 2019, but California, Massachusetts, New Jersey, Rhode Island and Washington, D.C. require coverage and may charge a tax penalty. Some visas require specific coverage.',
    covered: [
      'Emergency care and hospital stays',
      'Doctor visits and specialists, often with a [[copay]]',
      'Prescription drugs, depending on the plan\'s drug list',
      'Preventive care, like checkups, vaccines and screenings, free in-network under ACA plans',
      'Pregnancy and childbirth, mental health, lab tests, and children\'s dental and vision. These are required in individual and small-group plans; most large employer plans cover them too.',
      'Pre-existing conditions: ACA plans can\'t exclude them or charge you more for them',
    ],
    notCovered: [
      'Adult dental and vision care, which are usually separate plans',
      'Care outside the plan\'s [[network]], for [[hmo|HMO]] and [[epo|EPO]] plans, except emergencies',
      'Treatments needing [[prior-auth|prior authorization]] if you didn\'t get it',
      'Cosmetic procedures',
      'Long-term care, like a nursing home stay',
      'Most care outside the US',
    ],
    examples: [
      { s: 'You have a $10,000 surgery. Your plan has a $2,000 deductible, 20% coinsurance and a $6,000 out-of-pocket maximum.', v: 'yes', a: 'You pay the first $2,000 (your [[deductible]]), then 20% of the remaining $8,000, which is $1,600. Your total is $3,600; the plan pays $6,400. Once you\'ve paid $6,000 in the year, the plan pays 100% until the year ends.' },
      { s: 'You go to the emergency room at an out-of-network hospital.', v: 'yes', a: 'Plans must cover emergency care at in-network prices, and federal law (the No Surprises Act) protects you from most surprise out-of-network bills for emergencies.' },
      { s: 'You see a specialist without a referral on an HMO plan.', v: 'no', a: '[[hmo|HMO]] plans usually require your primary care doctor to refer you first. Without the referral, you may pay the full bill.' },
      { s: 'You get a filling at the dentist.', v: 'no', a: 'Adult dental care isn\'t part of most medical plans. A separate dental plan usually covers cleanings fully and fillings partly.' },
    ],
    partsTitle: 'What you pay, in order',
    partsIntro: 'Health plans share costs with you in stages. Knowing these four numbers tells you most of what a plan will cost.',
    parts: [
      { code: '1', name: 'Premium', short: 'What you pay every month', more: ['You pay it whether or not you see a doctor. Employers usually pay part of it and take your share from your paycheck.'] },
      { code: '2', name: 'Deductible', short: 'What you pay before the plan pays', more: ['For most services you pay the full price, at the plan\'s negotiated rate, until you reach the deductible. Preventive care and many copay services are exempt.'] },
      { code: '3', name: 'Copay and coinsurance', short: 'Your share after that', more: ['A [[copay]] is a flat amount, like $30 a visit. [[coinsurance|Coinsurance]] is a percentage, like 20% of the bill.'] },
      { code: '4', name: 'Out-of-pocket maximum', short: 'The most you pay in a year', more: ['After you reach it, the plan pays 100% of covered in-network care for the rest of the year. Premiums don\'t count toward it.'] },
    ],
    tables: [
      {
        heading: 'Where coverage comes from',
        title: 'Sources of health coverage in the US',
        head: ['Source', 'Who it\'s for', 'Good to know'],
        rows: [
          ['Employer plan', 'Employees and their families', 'The most common source. The employer usually pays a large share. Coverage typically ends when the job does.'],
          ['[[marketplace|Marketplace]] (HealthCare.gov or your state\'s site)', 'People without an affordable job-based plan', 'Help with premiums depends on income and immigration status. Sign up in [[open-enrollment]] or after a life event.'],
          ['Medicaid / CHIP', 'People with low incomes, and children', 'Run by each state, with different rules. A 2025 federal law narrowed eligibility for many non-citizens from October 2026; most green-card holders must wait 5 years. Emergency care is still covered.'],
          ['Medicare', 'People 65+ and some with disabilities', 'Federal. Premium-free hospital coverage (Part A) usually needs 10 years of US work history, yours or a spouse\'s.'],
          ['[[cobra|COBRA]]', 'People who just left a job', 'Keeps the same plan, usually for up to 18 months, but you pay the full cost plus up to 2%. Applies to employers with 20 or more employees; many states have similar rules for smaller ones.'],
          ['Short-term plans', 'Temporary gaps', 'Not ACA plans: they can refuse pre-existing conditions and cap benefits.'],
        ],
        note: 'Health coverage rules, especially eligibility for help with premiums, change often. Check [HealthCare.gov](https://www.healthcare.gov/) for the current year.',
      },
      {
        heading: 'Plan types',
        title: 'Health plan types',
        head: ['Type', 'Out-of-network care', 'Referral to see a specialist'],
        rows: [
          ['[[hmo|HMO]]', 'Not covered, except emergencies', 'Usually required'],
          ['[[epo|EPO]]', 'Not covered, except emergencies', 'Usually not required'],
          ['[[ppo|PPO]]', 'Partly covered, at a higher cost', 'Not required'],
          ['POS', 'Partly covered', 'Usually required'],
          ['[[hdhp|HDHP]]', 'Depends on the network type', 'Depends. Can be paired with an [[hsa|HSA]].'],
        ],
      },
    ],
    more: [
      { title: 'Reading your bills', body: ['After a visit, your plan sends an [[eob|explanation of benefits]]. It is not a bill. Compare it with the provider\'s bill before paying: the amount you owe should match.'] },
      { title: 'Dental and vision', body: ['Dental plans usually cover cleanings in full, fillings at 70 to 80%, and major work like crowns at about 50%, with a low yearly maximum, often $1,000 to $2,000. Vision plans cover an eye exam and part of glasses or contacts.'] },
    ],
    check: ['Your premium, deductible and out-of-pocket maximum', 'Plan type (HMO, PPO, EPO) and whether your doctors are in network', 'Whether your regular prescriptions are on the drug list', 'When coverage ends if you leave your job'],
    related: ['disability', 'life', 'travel'],
  },

  {
    slug: 'life',
    line: 'personal',
    group: 'Health, life and income',
    name: 'Life insurance',
    short: 'Life',
    codes: 'Term, whole, universal',
    teaser: 'Money for your family if you die.',
    keywords: ['death', 'term', 'whole life', 'beneficiary', 'family'],
    lead: 'Pays a set amount of money to the people you choose if you die, so your family can keep paying the mortgage, childcare or school.',
    forWho: 'People whose family depends on their income or unpaid work, such as parents, and people with shared debts like a mortgage.',
    required: 'No. Employers often include a small amount, often one or two times your salary, which usually ends when you leave the job.',
    covered: ['Death from almost any cause, including illness and accidents', 'Payment to your [[beneficiary|beneficiaries]], usually tax-free'],
    notCovered: [
      'Suicide in the first two years of the policy (one year in some states)',
      'Death when the application contained false answers, if the insurer finds out within the contestability period, usually two years',
      'Death after a [[term-life|term policy]] has ended',
      'Some policies exclude dangerous activities, like private flying',
    ],
    examples: [
      { s: 'A parent with a 20-year term policy dies of cancer in year 8.', v: 'yes', a: 'The full amount is paid to the beneficiaries. Illness is covered like any other cause.' },
      { s: 'Your 20-year term policy ended last year.', v: 'no', a: 'A term policy only pays during its term. Many can be renewed or converted, at a higher price.' },
    ],
    tables: [
      {
        heading: 'Term or permanent?',
        title: 'Term and permanent life insurance compared',
        head: ['Compare', '[[term-life|Term]]', '[[permanent-life|Permanent (whole, universal)]]'],
        rows: [
          ['How long', 'A set period, like 20 or 30 years', 'For life, as long as premiums are paid'],
          ['Cost for the same payout', 'Low', 'Many times higher'],
          ['Savings part', 'None', 'Builds cash value you can borrow against'],
          ['Typical use', 'Replacing income while children grow up or a mortgage is paid', 'Estate planning, or lifelong dependents'],
        ],
      },
    ],
    check: ['The amount and the end date', 'Who the beneficiaries are, and that they\'re up to date', 'Whether your work life insurance ends if you change jobs'],
    related: ['disability', 'health'],
  },

  {
    slug: 'disability',
    line: 'personal',
    group: 'Health, life and income',
    name: 'Disability insurance',
    short: 'Disability',
    codes: 'Short-term, long-term',
    teaser: 'Part of your income if you can\'t work.',
    keywords: ['income protection', 'sick', 'injury', 'short-term disability', 'long-term disability', 'paycheck'],
    lead: 'Replaces part of your paycheck, usually 50 to 70%, if an illness or injury keeps you from working, whether it happened at work or not.',
    forWho: 'Anyone who relies on their paycheck. Illness is far more common than accidents as a cause.',
    required: 'Not by law, except that a few states, including California, New York, New Jersey, Rhode Island and Hawaii, run short-term disability programs paid through payroll.',
    covered: ['Illness or injury that stops you from working, on or off the job', 'Pregnancy and recovery from childbirth, under most short-term policies', 'Part of your income, after the [[elimination-period]]'],
    notCovered: ['The first days or months, the [[elimination-period]]', 'Your full salary', 'Pre-existing conditions, in the first year of many policies', 'Self-inflicted injuries'],
    examples: [
      { s: 'You break your leg skiing and can\'t work for 10 weeks.', v: 'yes', a: 'Short-term disability pays part of your salary after its waiting period, often one to two weeks. Workers\' comp wouldn\'t apply, because it happened off the job.' },
      { s: 'A back injury keeps you from working for two years.', v: 'yes', a: 'Long-term disability usually starts after 90 or 180 days and can pay for years. Check whether it pays if you can\'t do **your** job ("own occupation") or only if you can\'t do **any** job.' },
    ],
    check: ['The waiting period', 'The percentage of salary and the monthly maximum', '"Own occupation" or "any occupation"', 'Whether the benefit is taxable (it usually is if your employer paid the premium, or you paid it with pre-tax money)'],
    related: ['health', 'life', 'workers-comp'],
  },

  {
    slug: 'travel',
    line: 'personal',
    group: 'Travel and pets',
    name: 'Travel insurance',
    short: 'Travel',
    codes: 'Trip cancellation, delay, medical',
    teaser: 'Cancelled trips, delays, lost bags and medical care abroad.',
    keywords: ['trip', 'cancellation', 'interruption', 'delay', 'flight', 'baggage', 'luggage', 'vacation', 'cfar', 'evacuation', 'abroad'],
    lead: 'Refunds prepaid trip costs if you have to cancel or cut a trip short for a listed reason, and pays for delays, lost bags and medical emergencies while traveling.',
    forWho: 'Travelers with expensive non-refundable bookings, and anyone traveling abroad whose health plan doesn\'t cover them there.',
    required: 'No, though some countries and visas require travel medical coverage for visitors.',
    covered: [
      'Cancelling for a [[covered-reason]], like your or a close family member\'s illness, a hurricane at your destination, or jury duty',
      'Coming home early for a covered reason, and the extra flight',
      'Meals and a hotel when you\'re delayed for a covered reason, after a set number of hours',
      'Essentials you buy while your bag is delayed, and lost or damaged bags up to a limit',
      'Emergency medical care abroad, and medical evacuation',
    ],
    notCovered: [
      'Changing your mind, or being worried about going, unless you bought [[cfar|cancel for any reason]]',
      'Events that were known when you bought the policy, like a hurricane that had already been named',
      '[[pre-existing|Pre-existing conditions]], unless you got a waiver by buying soon after booking',
      'Refunds the airline or hotel already owes you',
      'Risky activities, like extreme sports, unless added',
    ],
    examples: [
      { s: 'You get the flu three days before your trip and can\'t go.', v: 'yes', a: 'Illness with a doctor\'s note is a standard [[covered-reason]]. You get back the non-refundable costs you insured.' },
      { s: 'Your flight is delayed overnight because of a mechanical problem.', v: 'yes', a: 'Travel delay usually pays for a hotel and meals once the delay passes a threshold, often 6 to 12 hours, up to a daily limit. Keep receipts. Many airlines promise meals or a hotel for delays they cause, but federal law doesn\'t require it.' },
      { s: 'You decide you don\'t feel like going anymore.', v: 'no', a: 'Only [[cfar|cancel for any reason]] covers this, and it usually refunds 50 to 75% of the cost.' },
      { s: 'You book after a hurricane is named, then cancel because of it.', v: 'no', a: 'Once a storm is named, it\'s a known event and not covered for policies bought afterward. Buy insurance soon after booking.' },
      { s: 'The airline cancels your flight and you choose not to rebook.', v: 'depends', a: 'You usually don\'t need insurance for this: on flights to, from or within the US, the airline must refund the ticket in cash. Insurance may cover other prepaid costs, like a hotel, if the cancellation was for a covered reason.' },
      { s: 'You break your leg skiing in Switzerland.', v: 'yes', a: 'Travel medical pays for treatment abroad, if the policy includes it and skiing isn\'t excluded. Many US health plans pay little abroad, and Medicare usually pays nothing.' },
    ],
    partsTitle: 'The parts of a travel policy',
    partsIntro: 'A travel policy is a bundle. Plans differ a lot, so check which of these you have and their limits.',
    parts: [
      { code: '1', name: 'Trip cancellation', short: 'Before you leave', more: ['Refunds prepaid, non-refundable costs if you cancel for a [[covered-reason]]. Only the reasons listed count; read the list.'] },
      { code: '2', name: 'Trip interruption', short: 'Coming home early', more: ['Pays for the unused part of the trip and the extra cost of getting home, if you have to cut the trip short for a covered reason.'] },
      { code: '3', name: 'Travel delay', short: 'Stuck on the way', more: ['Pays reasonable meals and hotels after a minimum delay, for reasons like weather or a carrier problem, up to a daily maximum.'] },
      { code: '4', name: 'Baggage delay and loss', short: 'Your bags', more: ['Delay pays for essentials, like clothes and toiletries, after a bag is late by a set number of hours. Loss pays up to a limit, often with low caps for electronics and jewelry. The airline is responsible first.'] },
      { code: '5', name: 'Emergency medical', short: 'Care while abroad', more: ['Doctor and hospital bills while traveling. Some plans pay the hospital directly; others reimburse you.'] },
      { code: '6', name: 'Medical evacuation', short: 'Getting to proper care', more: ['Transport to an adequate hospital, or home, which can cost $50,000 or more from a remote place.'] },
      { code: 'Add-on', name: 'Cancel for any reason', short: 'Optional upgrade', more: ['[[cfar|CFAR]] lets you cancel for any reason at all and get back part of your costs. It usually must be bought within 14 to 21 days of your first payment, and you must cancel at least 2 days before departure.'] },
    ],
    more: [
      { title: 'Check your credit card first', body: ['Many travel credit cards include trip delay, trip cancellation, baggage and rental car coverage when you pay for the trip with that card. It\'s often narrower than a travel policy, but it may be enough for a short domestic trip.'] },
      { title: 'Travel medical for visitors to the US', body: ['Visitors and new arrivals often buy "visitor" or "travel medical" insurance. It isn\'t full health insurance: it covers emergencies, often excludes pre-existing conditions, and has limits. People settling in the US need real [health insurance](/personal/health/).'] },
    ],
    check: ['The list of [[covered-reason|covered reasons]]', 'How many hours before delay coverage starts, and the daily limit', 'The medical and evacuation limits', 'The deadline to get a [[pre-existing]] waiver or CFAR'],
    related: ['health', 'renters', 'home'],
  },

  {
    slug: 'pet',
    line: 'personal',
    group: 'Travel and pets',
    name: 'Pet insurance',
    short: 'Pet',
    codes: 'Accident and illness',
    teaser: 'Vet bills for your dog or cat.',
    keywords: ['dog', 'cat', 'vet', 'veterinary', 'animal'],
    lead: 'Reimburses part of your vet bills when your pet is injured or gets sick. You pay the vet first and send the claim.',
    forWho: 'Pet owners who\'d struggle with a sudden bill of several thousand dollars.',
    required: 'No.',
    covered: ['Accidents, like a swallowed toy or a broken leg', 'Illnesses, like cancer or diabetes, on accident-and-illness plans', 'Tests, surgery, hospital stays and medication for covered conditions'],
    notCovered: ['Conditions your pet had before the policy started', 'Illness in the first days or weeks, the [[waiting-period]]', 'Routine checkups and vaccines, unless you add a wellness plan', 'Harm your pet causes others, which falls under your [home](/personal/home/) or [renters](/personal/renters/) liability'],
    examples: [
      { s: 'Your dog tears a knee ligament and needs a $5,000 surgery.', v: 'depends', a: 'Usually covered, but many plans have a 6-month waiting period for knee ligament problems. With a $500 deductible and 80% reimbursement, you\'d get back $3,600.' },
      { s: 'Your dog bites a visitor.', v: 'no', a: 'Pet insurance only covers your pet\'s care. The visitor\'s claim goes to your home or renters liability coverage.' },
    ],
    check: ['Deductible, reimbursement percentage and yearly limit', 'Waiting periods', 'What counts as pre-existing'],
    related: ['renters', 'home'],
  },
];
