// Personal lines: home and property policies.
// Field guide for policy objects (all pages render in the same order):
//   lead      one sentence: what it's for (shown first, bold type)
//   forWho / required   the two quick facts
//   covered / notCovered  always visible side by side
//   examples  { s: situation, v: 'yes' | 'no' | 'depends', a: answer }
//   parts     coverage parts, shown as expandable rows
//   tables, more, check, related

const G = 'Your home and things';

export const home = [
  {
    slug: 'home',
    line: 'personal',
    group: G,
    name: 'Homeowners insurance',
    short: 'Home (HO-3)',
    codes: 'HO-3, HO-5, HO-2, HO-8',
    teaser: 'The house you own, your belongings, and your liability.',
    keywords: ['house', 'homeowner', 'ho3', 'ho-3', 'ho5', 'dwelling', 'coverage a', 'mortgage'],
    lead: 'Pays to repair or rebuild your house and replace your belongings after sudden damage like a fire or a burst pipe, and protects you if someone is hurt and blames you.',
    forWho: 'People who own and live in a house. Most policies are an **HO-3**; the other forms are compared below.',
    required: 'Not by law. Your mortgage lender requires it until the loan is paid off. Lenders that are federally regulated or backed also require flood insurance if the house is in a high-risk [[flood-zone]].',
    covered: [
      'Sudden damage to the house from fire, wind, hail, lightning, a burst pipe, a fallen tree, and any other cause that isn\'t excluded',
      'Your belongings, if damaged by one of the [16 named perils](/perils/), including theft, at home or anywhere else',
      'Hotel and other extra costs while you can\'t live in the house after covered damage',
      'Claims against you if you, your family or your pet hurt someone or damage their things, at home or away',
      'Small medical bills for guests hurt at your place, whoever was at fault',
    ],
    notCovered: [
      '**Flood**, meaning water rising from outside, including storm surge. You need a separate [flood policy](/personal/flood/).',
      '**Earthquake** and other ground movement. You need a separate [earthquake policy](/personal/earthquake/).',
      'Wear and tear, rot, rust, and anything caused by poor maintenance',
      'Slow leaks that go on for weeks or months, and the mold that follows',
      'Sewer or drain backup, unless you add [[water-backup]]',
      'Termites, rodents and other pests',
      'Your car, which [auto insurance](/personal/auto/) covers, and most business equipment and business activities',
      'Injuries to you and your household, which health insurance covers',
    ],
    examples: [
      { s: 'A pipe bursts in January and water pours into the kitchen.', v: 'yes', a: 'Sudden water damage from inside the house is covered: Coverage A pays for floors and cabinets, Coverage C for your belongings. The broken pipe itself usually isn\'t. If the pipe froze because you left the house unheated, the claim can be denied.' },
      { s: 'Heavy rain makes a creek overflow and water fills your basement.', v: 'no', a: 'That is flood, and a home policy excludes it however much damage it does. Only a separate flood policy pays.' },
      { s: 'A tree falls on the roof during a windstorm.', v: 'yes', a: 'Repairs to the house are covered, and so is removing the tree from it. A tree that falls without hitting anything is usually only removed if it blocks your driveway, up to a small amount.' },
      { s: 'Your roof leaks because the shingles are 25 years old.', v: 'no', a: 'Old age and wear aren\'t covered. If a storm had torn shingles off, the storm damage would be.' },
      { s: 'Your laptop is stolen from your car.', v: 'yes', a: 'Belongings are covered away from home too, minus your deductible. The broken car window falls under your car\'s [[comprehensive]] coverage instead.' },
      { s: 'A guest slips on your icy front steps and breaks a wrist.', v: 'yes', a: 'Coverage F can pay small medical bills right away, whoever was at fault. If they sue, Coverage E pays your legal defense and any amount you\'re found to owe, up to the limit.' },
    ],
    partsTitle: 'The six parts of a homeowners policy (A to F)',
    partsIntro: 'Your [[declarations]] page lists a limit for each part. Open one to see what it means.',
    parts: [
      {
        code: 'A', name: 'Dwelling', short: 'The house itself',
        more: [
          'The structure and everything built into it: roof, walls, floors, built-in cabinets, plumbing, wiring, and an attached garage.',
          'In an HO-3 it\'s [[open-perils]]: every cause of damage is covered unless the policy excludes it.',
          'Set this limit at what it would cost to **rebuild** the house, not what you paid or what it would sell for. Land isn\'t included, because land doesn\'t burn.',
        ],
        example: 'A kitchen fire destroys the cabinets and blackens the ceiling. Coverage A pays to repair them.',
      },
      {
        code: 'B', name: 'Other structures', short: 'Detached garage, shed, fence',
        more: ['Buildings and structures on your property that aren\'t attached to the house. Usually set at 10% of Coverage A.', 'Structures you rent out or use for a business are usually excluded.'],
        example: 'A windstorm flattens 60 feet of fence.',
      },
      {
        code: 'C', name: 'Personal property', short: 'Your belongings',
        more: [
          'Furniture, clothes, electronics, kitchenware, bikes. Covered at home and while traveling.',
          'In an HO-3 this is [[named-perils]]: only the [16 listed causes](/perils/) are covered. Accidentally dropping your TV isn\'t one of them.',
          'Usually 50 to 70% of Coverage A. Watch the [[sublimit|sublimits]]: cash is often capped around $200, jewelry theft around $1,500. Check whether it pays [[replacement-cost]] or [[acv|actual cash value]].',
        ],
        example: 'A burglar takes a TV, a laptop and a bike. You list them, with receipts or photos if you have them, and are paid up to the limit minus the deductible.',
      },
      {
        code: 'D', name: 'Loss of use', short: 'Living costs while you can\'t live there',
        more: ['Pays the **extra** cost of living elsewhere after covered damage: rent, a hotel, and meals above your normal grocery bill. It doesn\'t pay costs you\'d have anyway, like your mortgage.'],
        example: 'A fire makes the house unlivable for three months. The policy pays for a rental apartment and the extra cost of eating out.',
      },
      {
        code: 'E', name: 'Personal liability', short: 'If you\'re blamed for harm to others',
        more: [
          'Pays other people\'s claims, and your lawyers, if you or your household are legally responsible for injuring someone or damaging their property. Usually $100,000 to $500,000.',
          'It follows you anywhere, not just at home. It doesn\'t cover car accidents, business activities or harm you meant to cause.',
        ],
        example: 'Your dog knocks over a cyclist, who sues for medical bills and lost wages.',
      },
      {
        code: 'F', name: 'Medical payments to others', short: 'A guest\'s small medical bills',
        more: ['Pays a guest\'s medical bills if they\'re hurt at your place or by your pet, whoever was at fault. Usually $1,000 to $5,000. It often settles things before anyone thinks about suing. It never pays for you or your household.'],
        example: 'A friend\'s child falls off your swing set and needs stitches.',
      },
    ],
    tables: [
      {
        heading: 'HO-3, HO-5 and the other forms',
        intro: 'The "HO" number tells you the form the policy is based on. The main difference is whether damage is covered by [[named-perils]] (only listed causes) or [[open-perils]] (any cause not excluded).',
        title: 'Homeowners policy forms compared',
        head: ['Form', 'Made for', 'The house', 'Your belongings'],
        rows: [
          ['HO-2 (broad)', 'Owners wanting a cheaper policy', 'Named perils', 'Named perils'],
          ['**HO-3 (special)**', 'Most owners. The most common form', '**Open perils**', 'Named perils'],
          ['HO-5 (comprehensive)', 'Owners wanting the broadest cover', 'Open perils', '**Open perils**'],
          ['HO-8 (modified)', 'Older homes that would cost far more to rebuild than they\'re worth', 'Basic named perils, often paid at [[acv|actual cash value]]', 'Basic named perils'],
          ['HO-4', '[Renters](/personal/renters/)', 'Not included', 'Named perils'],
          ['HO-6', '[Condo owners](/personal/condo/)', 'Your unit\'s interior', 'Named perils'],
        ],
        note: 'These are the standard forms most insurers base their policies on. Insurers change the wording, so two HO-3 policies can differ. Mobile homes use their own forms.',
      },
    ],
    more: [
      { title: 'How much dwelling coverage do I need?', body: ['Enough to rebuild the house from the ground up at today\'s labor and material prices. That can be more or less than the market price. Ask whether your policy has "extended replacement cost", which adds 20 to 50% on top if rebuilding costs spike after a disaster.'] },
      { title: 'Separate deductibles for wind, hail and hurricanes', body: ['In storm-prone states, policies often have a separate [[wind-deductible]] set as a percentage of Coverage A. On a $400,000 house, a 2% hurricane deductible means you pay the first $8,000.'] },
      { title: 'Jewelry, art and other valuables', body: ['Theft of jewelry is usually capped at around $1,500 in total. To cover an engagement ring or a collection properly, list it as [[scheduled-property]] with an appraisal. Scheduled items are often covered for simply losing them, too.'] },
      { title: 'Working or running a business from home', body: ['Home policies cover very little business property (often $2,500 at home) and no business liability. A client tripping on your stairs or a stolen work laptop may not be covered. Ask about a home-business endorsement or a [business owner\'s policy](/business/bop/).'] },
      { title: 'Older roofs and hail', body: ['Many policies now pay older roofs at [[acv|actual cash value]], or exclude cosmetic hail damage like dents that don\'t cause leaks. Look for a roof endorsement on your [[declarations]] page.'] },
      { title: 'If no insurer will cover you', body: ['In high-risk areas, private insurers may decline a home. State FAIR plans, Citizens in Florida, and state wind pools offer basic coverage as a last resort. It is often narrower and more expensive, so compare what it leaves out.'] },
      { title: 'Small claims and your insurance record', body: ['Claims, even small ones, are recorded in a shared industry database (CLUE) and can raise your premium or lead the insurer not to renew. Check your policy\'s rules on reporting before deciding not to report something.'] },
      { title: 'Rebuilding to current building codes', body: ['After a big loss, the city may require upgrades like new wiring or a sprinkler system. Standard policies pay only a little toward that, often 10% of Coverage A. [[ordinance-or-law|Ordinance or law coverage]] raises it.'] },
    ],
    check: [
      'Which form it is: HO-3, HO-5 or another',
      'Coverage A: would it rebuild the house at today\'s prices?',
      'Whether belongings are paid at [[replacement-cost]] or [[acv|actual cash value]]',
      'Your [[deductible]], and any separate [[wind-deductible|wind or hurricane deductible]]',
      'Whether [[water-backup]] is included',
      '[[sublimit|Sublimits]] for jewelry, electronics, bikes or collections',
      'Your liability limit, and whether an [umbrella policy](/personal/umbrella/) would make sense',
    ],
    related: ['flood', 'earthquake', 'umbrella', 'renters', 'condo', 'landlord'],
  },

  {
    slug: 'renters',
    line: 'personal',
    group: G,
    name: 'Renters insurance',
    short: 'Renters (HO-4)',
    codes: 'HO-4',
    teaser: 'Your belongings and liability when you rent.',
    keywords: ['tenant', 'apartment', 'rent', 'ho4', 'ho-4', 'contents'],
    lead: 'Covers your belongings and your liability when you rent a home. The landlord\'s insurance covers the building, not your things and not you.',
    forWho: 'Anyone renting an apartment, house or room. It\'s usually one of the cheapest policies you can buy.',
    required: 'Not by law, but many leases require it, often with at least $100,000 of liability coverage.',
    covered: [
      'Your belongings, if damaged by one of the [16 named perils](/perils/) such as fire, smoke, theft or a burst pipe, at home or away',
      'Hotel and extra costs if the apartment can\'t be lived in after covered damage',
      'Claims against you if you hurt someone or damage other people\'s property, like a bathtub overflow that ruins the unit below. Damage to the unit you rent is usually covered only if caused by fire, smoke or explosion.',
      'Small medical bills for guests hurt at your place',
    ],
    notCovered: [
      'The building itself, walls, floors and built-in appliances. That\'s the landlord\'s insurance.',
      '**Flood** and **earthquake**',
      'Your roommate\'s things, unless they\'re named on your policy',
      'Bedbugs, rodents and other pests',
      'Your car, though things stolen from your car are covered',
      'Expensive items above the [[sublimit|sublimits]], such as jewelry or cash',
    ],
    examples: [
      { s: 'A fire in the next unit fills your apartment with smoke.', v: 'yes', a: 'Smoke is a named peril. Cleaning or replacing your clothes and furniture is covered, and so is a hotel while the smell is being dealt with.' },
      { s: 'You leave the bath running and water leaks into the apartment below.', v: 'yes', a: 'Your liability coverage usually pays for the neighbor\'s damage if you\'re responsible. Damage to your own rented unit is usually covered only when caused by fire, smoke or explosion, so the landlord\'s insurer may seek the rest from you.' },
      { s: 'Your bike is stolen from outside a café.', v: 'yes', a: 'Theft is covered away from home, minus your deductible. With a $500 deductible, a cheap bike may not be worth claiming.' },
      { s: 'You find bedbugs in your mattress.', v: 'no', a: 'Pest damage and extermination are excluded. Depending on your state and lease, the landlord may have to pay for treatment.' },
      { s: 'The roof leaks during a storm and ruins your couch.', v: 'depends', a: 'If wind or hail damaged the roof and rain came in through that opening, your couch is usually covered. If the roof leaked because of poor upkeep, your policy may not pay, but the landlord may be responsible.' },
    ],
    partsTitle: 'What\'s inside a renters policy',
    partsIntro: 'Renters policies use the same letters as homeowners policies but skip A and B, the building parts.',
    parts: [
      { code: 'C', name: 'Personal property', short: 'Your belongings', more: ['Everything you own in the apartment and when you travel. A quick video of every room makes a claim much easier. [[replacement-cost|Replacement cost]] costs a little more; [[acv|actual cash value]] pays little for used furniture.'], example: 'A kitchen fire ruins your furniture and clothes.' },
      { code: 'D', name: 'Loss of use', short: 'Where you stay meanwhile', more: ['Extra living costs if the unit is unlivable after covered damage, above what you normally pay.'] },
      { code: 'E', name: 'Personal liability', short: 'Harm you cause', more: ['Claims for injuries or damage you\'re responsible for, anywhere, plus your legal defense.'], example: 'Your space heater starts a fire that spreads to the hallway.' },
      { code: 'F', name: 'Medical payments to others', short: 'Guests\' small medical bills', more: ['A visitor\'s medical bills if they\'re hurt at your place, whoever was at fault.'] },
    ],
    more: [
      { title: 'What does the landlord\'s policy cover?', body: ['The building and the landlord\'s own liability. It won\'t replace your belongings, pay for your hotel, or defend you if a guest sues you. If you damage the building, the landlord\'s insurer can pay the landlord and then come after you through [[subrogation]].'] },
      { title: 'Roommates and partners', body: ['Relatives living with you are usually covered automatically. A roommate or unmarried partner usually isn\'t, unless they\'re added by name. It\'s often simpler for each person to have their own policy.'] },
    ],
    check: [
      'Your personal property limit: would it replace everything you own?',
      '[[replacement-cost]] or [[acv|actual cash value]]',
      'Your [[deductible]]',
      'Liability limit, and whether it meets your lease\'s requirement',
      'Who is named on the policy',
    ],
    related: ['home', 'flood', 'umbrella', 'auto'],
  },

  {
    slug: 'condo',
    line: 'personal',
    group: G,
    name: 'Condo insurance',
    short: 'Condo (HO-6)',
    codes: 'HO-6',
    teaser: 'The inside of your unit, your things and your liability.',
    keywords: ['condominium', 'hoa', 'unit', 'ho6', 'ho-6', 'master policy', 'co-op'],
    lead: 'Covers the inside of your condo unit, your belongings and your liability. The association\'s [[master-policy]] covers the building and shared areas.',
    forWho: 'People who own a condominium or co-op unit.',
    required: 'Not by law. Your mortgage lender will require it, and many condo associations require it in their bylaws.',
    covered: [
      'The parts of the unit the master policy leaves to you, often floors, cabinets, fixtures and any upgrades you made',
      'Your belongings, from the [16 named perils](/perils/)',
      'Extra living costs if the unit is unlivable after covered damage',
      'Your share of a special charge the association passes to owners after a big loss, through [[loss-assessment]] coverage',
      'Claims if you hurt someone or damage a neighbor\'s unit',
    ],
    notCovered: [
      'The building structure, roof and common areas, which the association\'s master policy covers',
      '**Flood** and **earthquake**',
      'Wear and tear, slow leaks and mold',
      'Sewer or drain backup, unless added',
      'Pests',
    ],
    examples: [
      { s: 'Your washing machine hose bursts and floods the unit below.', v: 'yes', a: 'Your unit\'s floors and belongings are covered under your HO-6. Your liability coverage pays for the neighbor\'s damage if you\'re responsible.' },
      { s: 'A storm damages the roof, and the association charges each owner $4,000 toward its deductible.', v: 'yes', a: '[[loss-assessment|Loss assessment]] coverage pays your share, up to its limit. Many policies include only $1,000. Assessments that come from the association\'s deductible are often capped separately, even if you raise the limit.' },
      { s: 'You remodeled the kitchen, and a fire destroys it.', v: 'depends', a: 'Your upgrades are usually yours to insure. If your unit coverage limit is too low to cover the remodel, you pay the difference.' },
    ],
    partsTitle: 'What\'s inside a condo policy',
    parts: [
      { code: 'A', name: 'Dwelling (your unit)', short: 'Walls in, as the bylaws define', more: ['How much you need depends on the master policy. A "bare walls" master policy leaves everything inside the walls to you. An "all-in" master policy covers the original fixtures, leaving you only your upgrades. Ask the association for a copy.'] },
      { code: 'C', name: 'Personal property', short: 'Your belongings', more: ['Your furniture, clothes and electronics, at home or away.'] },
      { code: 'D', name: 'Loss of use', short: 'Where you stay meanwhile', more: ['Extra living costs while the unit is being repaired.'] },
      { code: 'E', name: 'Personal liability', short: 'Harm you cause', more: ['Claims against you for injuries or property damage, including to neighbors\' units.'] },
      { code: 'F', name: 'Medical payments to others', short: 'Guests\' small medical bills', more: ['A visitor\'s medical bills, whoever was at fault.'] },
      { code: 'Add-on', name: 'Loss assessment', short: 'Your share of the association\'s costs', more: ['When a loss hits shared property and the master policy doesn\'t pay all of it, the association can bill owners. This coverage pays your share, up to its limit. Assessments from the association\'s deductible are often capped separately, sometimes at $1,000.'] },
    ],
    check: [
      'What the master policy covers: "bare walls", "single entity" or "all-in"',
      'The master policy\'s deductible, which the association may pass on to owners',
      'Your [[loss-assessment]] limit',
      'Coverage for upgrades you made',
      'Whether [[water-backup]] is included',
    ],
    related: ['home', 'renters', 'flood', 'umbrella'],
  },

  {
    slug: 'landlord',
    line: 'personal',
    group: G,
    name: 'Landlord insurance',
    short: 'Landlord (DP-3)',
    codes: 'DP-1, DP-2, DP-3',
    teaser: 'A home you rent out: the building and lost rent.',
    keywords: ['rental property', 'dwelling fire', 'dp3', 'dp-3', 'investment property', 'fair rental value', 'airbnb', 'tenant'],
    lead: 'Insures a house or unit you rent out: the building and the rent you lose after damage. It doesn\'t cover your tenant\'s belongings.',
    forWho: 'Owners of a home they rent to others. Also used for vacant homes and some second homes. The forms are called dwelling policies, **DP-1, DP-2 and DP-3**.',
    required: 'Not by law. A mortgage lender will require it. A regular homeowners policy usually stops covering the house once you move out and rent it.',
    covered: [
      'The building, from the causes your form covers. DP-3 covers any cause not excluded.',
      'Rent you lose while the home is unlivable after covered damage ([[fair-rental-value]])',
      'Your own things kept there for the tenants, like appliances or a lawn mower',
      'Liability, if you add it, for injuries caused by the property, like a broken stair',
    ],
    notCovered: [
      'Your tenant\'s belongings and liability. Tenants need their own [renters insurance](/personal/renters/).',
      '**Flood** and **earthquake**',
      'Damage from wear and tear, or poor maintenance',
      'Unpaid rent when a tenant simply stops paying, unless you add rent guarantee coverage',
      'Vandalism and some water damage once the home has been **vacant** for about 60 days in a row',
      'Short-term rentals like Airbnb, unless the policy says it covers them',
    ],
    examples: [
      { s: 'A kitchen fire forces your tenants out for two months.', v: 'yes', a: 'The policy pays to repair the house and the rent you lose while it\'s being fixed. The tenants\' belongings and hotel are for their renters insurance.' },
      { s: 'A tenant\'s guest falls on a loose stair and sues you.', v: 'depends', a: 'Covered only if you added liability to the policy. Dwelling policies don\'t always include it, so check. It\'s often called "Coverage L".' },
      { s: 'The house sits empty for three months between tenants and is vandalized.', v: 'no', a: 'After about 60 days of vacancy, most policies stop covering vandalism and glass breakage. Tell your insurer before a long vacancy; a vacancy endorsement can keep you covered.' },
    ],
    partsTitle: 'What\'s inside a dwelling (DP) policy',
    partsIntro: 'The letters look like a homeowners policy, but D and E mean different things, and liability is added separately.',
    parts: [
      { code: 'A', name: 'Dwelling', short: 'The rental building', more: ['The structure and what\'s built into it.'] },
      { code: 'B', name: 'Other structures', short: 'Garage, shed, fence', more: ['Detached structures on the property.'] },
      { code: 'C', name: 'Personal property', short: 'Your things at the rental', more: ['Items you own and keep there for the tenants, like appliances or furniture in a furnished rental. Optional in many policies.'] },
      { code: 'D', name: 'Fair rental value', short: 'Rent you lose', more: ['The rent you lose while the unit is unlivable after covered damage.'], example: 'Rent is $2,000 a month and repairs take three months: the policy pays up to $6,000.' },
      { code: 'E', name: 'Additional living expense', short: 'If you live there yourself', more: ['Only matters if you live in part of the building, like the other half of a duplex.'] },
      { code: 'L & M', name: 'Liability and medical payments', short: 'Often an add-on', more: ['Claims when someone is hurt because of the property. Not part of every dwelling policy; you may need to add it or buy a separate liability policy.'] },
    ],
    tables: [
      {
        heading: 'DP-1, DP-2 and DP-3',
        title: 'Dwelling policy forms compared',
        head: ['Form', 'Covered causes', 'How claims are paid'],
        rows: [
          ['DP-1 (basic)', 'A short list: fire, lightning and internal explosion. Wind, hail and a few others are often added.', 'Usually [[acv|actual cash value]]'],
          ['DP-2 (broad)', 'A longer [[named-perils|named-peril]] list, similar to HO-2', 'Usually [[replacement-cost]] for the building'],
          ['**DP-3 (special)**', '[[open-perils|Open perils]] for the building: any cause not excluded', 'Usually replacement cost for the building'],
        ],
        note: 'DP-3 is the most common choice for rented homes. DP-1 is cheaper, and often used for vacant or older homes.',
      },
    ],
    check: [
      'Which DP form you have',
      'Whether liability (L and M) is included, and its limit',
      'How long the home can sit vacant before coverage shrinks',
      'Whether short-term or furnished rentals are allowed',
      'That your lease requires tenants to carry renters insurance',
    ],
    related: ['home', 'renters', 'umbrella', 'flood'],
  },

  {
    slug: 'flood',
    line: 'personal',
    group: G,
    name: 'Flood insurance',
    short: 'Flood',
    codes: 'NFIP, private flood',
    teaser: 'Rising water, which home policies exclude.',
    keywords: ['flooding', 'storm surge', 'nfip', 'fema', 'flood zone', 'hurricane', 'basement', 'rain'],
    lead: 'Covers damage from rising water, which home, renters and condo policies all exclude. You buy it separately, usually through the federal [[nfip|NFIP]].',
    forWho: 'Homeowners, renters and businesses anywhere it can rain. More than 20% of flood claims come from outside high-risk zones.',
    required: 'Required by lenders if the home is in a high-risk [[flood-zone]] and the mortgage is federally backed. Optional everywhere else.',
    covered: [
      'The building, including its foundation, electrical and plumbing, furnace, water heater, and built-in appliances',
      'Your belongings, if you buy contents coverage. Renters can buy contents only.',
      'Cleanup such as debris removal',
    ],
    notCovered: [
      'Floods that begin in the first **30 days** after you buy the policy or raise its limits, the usual [[waiting-period]]. Exceptions apply, such as buying when you get a mortgage.',
      'Most contents in a basement, and finished basement walls and floors',
      'Hotel and living costs while you\'re displaced (NFIP policies)',
      'Water that seeps in because of poor drainage or a leak, rather than a flood',
      'Cars, which are covered by [[comprehensive]] on your auto policy',
      'Money, valuable papers, and land and landscaping',
    ],
    examples: [
      { s: 'A hurricane\'s storm surge pushes seawater into your ground floor.', v: 'yes', a: 'Storm surge is flood, so the flood policy pays. The wind damage to your roof from the same storm goes to your home policy, usually with a separate [[wind-deductible]].' },
      { s: 'You buy flood insurance the day before a forecast storm.', v: 'no', a: 'NFIP policies usually take 30 days to start, so they won\'t pay for this storm. The main exception: buying at the same time as your mortgage.' },
      { s: 'Your finished basement floods; the carpet, drywall and a sofa are ruined.', v: 'no', a: 'NFIP policies cover basement essentials like the furnace and water heater, but not finished walls, flooring or most belongings there.' },
    ],
    partsTitle: 'What\'s inside an NFIP flood policy',
    parts: [
      { code: 'Building', name: 'Building property', short: 'Up to $250,000 for a home', more: ['The structure and its systems. Paid at [[replacement-cost]] for a single-family main home insured for at least 80% of its rebuilding cost, or for the $250,000 maximum; otherwise at [[acv|actual cash value]].'] },
      { code: 'Contents', name: 'Personal property', short: 'Up to $100,000', more: ['Your belongings, bought separately. Always paid at actual cash value under the NFIP.'] },
    ],
    more: [
      { title: 'What counts as a "flood"?', body: ['The official definition is water covering at least two acres of normally dry land, or two or more properties, from overflowing water, unusual runoff, or mudflow. Water that only affects your house, like a burst pipe, isn\'t flood and goes to your home policy.'] },
      { title: 'Private flood insurance', body: ['Private insurers also sell flood policies. Some offer higher limits, shorter waiting periods, or living expenses. Lenders must accept private policies that meet federal standards.'] },
      { title: 'Federal disaster aid is not insurance', body: ['Disaster aid only comes if the President declares a disaster, and it\'s often a loan you must repay, or a small grant.'] },
    ],
    check: ['Your flood zone, at [FEMA\'s flood map](https://msc.fema.gov/portal/home)', 'Building and contents limits', 'The start date, allowing for the 30-day wait', 'What\'s in your basement'],
    related: ['home', 'renters', 'condo', 'earthquake'],
  },

  {
    slug: 'earthquake',
    line: 'personal',
    group: G,
    name: 'Earthquake insurance',
    short: 'Earthquake',
    codes: 'Policy or add-on',
    teaser: 'Shaking damage, which home policies exclude.',
    keywords: ['quake', 'california', 'cea', 'earth movement', 'sinkhole', 'landslide'],
    lead: 'Covers damage from an earthquake\'s shaking, which standard home policies exclude. It\'s bought as a separate policy or an add-on.',
    forWho: 'Anyone in an earthquake region: the West Coast, Alaska, and parts of the central US near the New Madrid fault. In California it\'s commonly sold through the California Earthquake Authority.',
    required: 'Not by law. Lenders rarely require it.',
    covered: [
      'Damage to the house from shaking, like cracked foundations and walls',
      'Your belongings, if you choose that coverage',
      'Extra living costs while the home is repaired',
    ],
    notCovered: [
      'The first 10 to 20% of the dwelling limit, the typical [[deductible]]',
      'Flooding caused by the quake, including tsunami. That\'s a flood policy.',
      'Your car, which [[comprehensive]] covers',
      'Landslides, mudflow and sinkholes, which need separate coverage',
    ],
    examples: [
      { s: 'An earthquake cracks your chimney and foundation.', v: 'yes', a: 'Covered by the earthquake policy, above its deductible. With a $500,000 limit and a 15% deductible, you pay the first $75,000.' },
      { s: 'The shaking breaks a gas line and your house catches fire.', v: 'yes', a: 'Fire is covered by your regular home policy even when an earthquake caused it.' },
    ],
    more: [
      { title: 'Why the deductible is so high', body: ['A big earthquake damages thousands of homes at once, so insurers share the risk with you through a percentage deductible. It still protects you from a total loss, which is what would be hardest to recover from.'] },
    ],
    check: ['Deductible percentage and what it is in dollars', 'Whether belongings and living costs are included', 'Whether retrofitting discounts apply'],
    related: ['home', 'flood', 'condo'],
  },
];
