// "Is it covered?" scenarios. short = the one-line answer shown first.
export const scenarios = [
  // Home
  { id: 'burst-pipe', label: 'Burst pipe', area: 'Home', q: 'A pipe bursts and floods my kitchen.', v: 'yes', short: 'Sudden water from inside the house is usually covered.', a: 'Home, condo and renters policies cover sudden, accidental water damage from plumbing. The broken pipe itself usually isn\'t replaced. A frozen pipe in a house left unheated can be excluded.', policies: ['home', 'renters', 'condo'], tags: ['water', 'leak', 'plumbing', 'frozen'] },
  { id: 'rain-basement', label: 'Flooded basement', area: 'Home', q: 'Heavy rain floods my basement.', v: 'no', short: 'Water from outside isn\'t covered by a home policy.', a: 'Home policies exclude surface water and groundwater seeping in. A flood policy pays only if the event meets the official flood definition, and even then covers little in a basement. If a sump pump overflowed, a [[water-backup]] endorsement may pay. Rain coming in through a storm-damaged roof or wall is covered by your home policy.', policies: ['flood', 'home'], tags: ['water', 'storm', 'rain', 'flooding'] },
  { id: 'sewer-backup', area: 'Home', q: 'Sewage backs up through a floor drain.', v: 'depends', short: 'Only if you added water backup coverage.', a: 'Standard policies exclude water that backs up through sewers or drains, or overflows a sump pump. A [[water-backup]] endorsement adds it, usually for a small extra premium.', policies: ['home'], tags: ['water', 'sump pump', 'drain'] },
  { id: 'slow-leak', area: 'Home', q: 'A slow leak under the sink caused mold over several months.', v: 'no', short: 'Slow, ongoing leaks and the mold they cause are excluded.', a: 'Policies cover sudden damage, not damage that builds up over time. Insurers expect you to notice and fix slow leaks. Some policies cover a little mold removal when it results from a covered sudden leak.', policies: ['home'], tags: ['mold', 'water', 'maintenance'] },
  { id: 'tree-on-house', area: 'Home', q: 'A tree falls on my house in a storm.', v: 'yes', short: 'Damage to the house and removing the tree from it are covered.', a: 'Your own policy pays, whoever owned the tree. If a neighbor ignored a visibly dead tree, your insurer may try to recover from them. A tree that falls without hitting anything is usually only removed up to a small amount.', policies: ['home'], tags: ['wind', 'storm', 'tree'] },
  { id: 'old-roof', area: 'Home', q: 'My old roof leaks.', v: 'no', short: 'Wear and tear isn\'t covered.', a: 'If the roof leaks because of age, the insurer treats it as maintenance. Storm damage to a roof is covered, though some policies pay only the depreciated value for older roofs.', policies: ['home'], tags: ['roof', 'maintenance', 'leak'] },
  { id: 'hail-roof', area: 'Home', q: 'Hail damages my roof.', v: 'yes', short: 'Hail is covered, minus your deductible.', a: 'In hail-prone states, there may be a separate wind and hail deductible, often a percentage of your dwelling limit. Some policies pay older roofs at [[acv|actual cash value]].', policies: ['home'], tags: ['storm', 'roof', 'wind'] },
  { id: 'ring-stolen', label: 'Ring stolen', area: 'Home', q: 'My engagement ring is stolen.', v: 'depends', short: 'Only up to a low limit, unless it\'s listed on your policy.', a: 'Jewelry theft is usually capped at around $1,500 in total. If the ring is listed as [[scheduled-property]], it\'s covered for its appraised value.', policies: ['home', 'renters'], tags: ['jewelry', 'theft', 'valuables'] },
  { id: 'ring-lost', area: 'Home', q: 'I lost my ring down the drain.', v: 'no', short: 'Simply losing something isn\'t a covered cause, unless it\'s scheduled.', a: 'Losing an item isn\'t one of the named perils. Items listed as [[scheduled-property]] are usually covered for loss too.', policies: ['home'], tags: ['jewelry', 'lost', 'valuables'] },
  { id: 'power-surge', area: 'Home', q: 'A power surge fries my TV.', v: 'depends', short: 'It depends on what caused the surge.', a: 'Lightning damage is covered. A surge from the power company is a named peril, but the standard wording excludes damage to electronic parts, so many TVs and computers aren\'t covered. Some insurers add surge coverage.', policies: ['home', 'renters'], tags: ['electronics', 'lightning', 'electric'] },
  { id: 'earthquake-crack', area: 'Home', q: 'An earthquake cracks my foundation.', v: 'no', short: 'Earthquakes are excluded; you need a separate policy.', a: 'Ground movement is excluded from standard home policies. An earthquake policy or add-on covers it, with a high percentage deductible. Fire caused by an earthquake is covered by the home policy.', policies: ['earthquake', 'home'], tags: ['quake', 'foundation'] },
  { id: 'wildfire-smoke', area: 'Home', q: 'Wildfire smoke damages my home and belongings.', v: 'yes', short: 'Fire and smoke are covered causes.', a: 'Fire and smoke are among the most basic covered perils. Extra living costs are covered if you have to leave, including when authorities order an evacuation because a covered cause like fire damaged nearby property, usually for up to two weeks.', policies: ['home', 'renters'], tags: ['fire', 'smoke', 'evacuation'] },
  { id: 'termites', area: 'Home', q: 'Termites damage the floor joists.', v: 'no', short: 'Pests are excluded.', a: 'Damage from termites, rodents and other pests is treated as a maintenance issue.', policies: ['home'], tags: ['pests', 'insects'] },
  { id: 'dog-bite', area: 'Home', q: 'My dog bites a neighbor.', v: 'yes', short: 'Personal liability usually covers it.', a: 'The liability part of your home or renters policy pays for the neighbor\'s injuries and your defense. Some insurers exclude certain breeds or dogs with a bite history, so check.', policies: ['home', 'renters'], tags: ['pet', 'animal', 'liability', 'injury'] },
  { id: 'guest-falls', area: 'Home', q: 'A guest slips on my steps and gets hurt.', v: 'yes', short: 'Medical payments and liability cover this.', a: 'Medical payments to others pays small bills whoever was at fault. If the guest sues, personal liability pays your defense and damages up to the limit.', policies: ['home', 'renters', 'condo'], tags: ['injury', 'liability', 'slip'] },
  { id: 'work-laptop-home', area: 'Home', q: 'My work laptop is stolen from my home.', v: 'depends', short: 'Not if it belongs to your employer; limited if it\'s your business\'s.', a: 'Your employer\'s property is for your employer\'s insurance. Your own business property is covered only up to a small limit, often $2,500 at home.', policies: ['home', 'bop'], tags: ['theft', 'business', 'computer', 'remote work'] },

  // Renting
  { id: 'bath-overflow', area: 'Renting', q: 'My bathtub overflows and damages the apartment below.', v: 'yes', short: 'Your renters liability covers the neighbor\'s damage.', a: 'If you\'re responsible, the liability part of your renters policy pays for the damage to the other unit. Damage to the unit you rent is usually covered only if caused by fire, smoke or explosion.', policies: ['renters'], tags: ['water', 'neighbor', 'liability'] },
  { id: 'neighbor-fire', area: 'Renting', q: 'A fire in another unit ruins my things with smoke.', v: 'yes', short: 'Your renters policy covers your belongings.', a: 'Smoke and fire are covered causes. The landlord\'s policy won\'t replace your things.', policies: ['renters'], tags: ['fire', 'smoke', 'apartment'] },
  { id: 'bedbugs', area: 'Renting', q: 'I have bedbugs.', v: 'no', short: 'Pests aren\'t covered.', a: 'Neither the treatment nor the ruined bedding is covered. Depending on your state and lease, the landlord may be responsible for treatment.', policies: ['renters'], tags: ['pests', 'insects'] },
  { id: 'roommate-stuff', area: 'Renting', q: 'My roommate\'s laptop is stolen from our apartment.', v: 'no', short: 'Not on your policy, unless they\'re named on it.', a: 'Renters policies cover you and relatives living with you. A roommate needs their own policy or to be added by name.', policies: ['renters'], tags: ['theft', 'roommate'] },

  // Car
  { id: 'deer', label: 'Hit a deer', area: 'Car', q: 'I hit a deer.', v: 'yes', short: 'Covered by comprehensive, if you carry it.', a: 'Animal strikes are [[comprehensive]] claims. If you swerve and hit a tree instead, that\'s [[collision]].', policies: ['auto'], tags: ['animal', 'crash'] },
  { id: 'my-fault-crash', area: 'Car', q: 'I cause a crash. Who pays for my car?', v: 'depends', short: 'Only your collision coverage pays for your own car.', a: 'Your liability coverage pays for the other driver\'s car and injuries. Your car is covered only if you carry [[collision]], minus the deductible.', policies: ['auto'], tags: ['accident', 'collision', 'fault'] },
  { id: 'uninsured-driver', area: 'Car', q: 'An uninsured driver hits me.', v: 'depends', short: 'Covered if you have uninsured motorist coverage.', a: '[[uninsured-motorist|Uninsured motorist]] coverage pays your injuries, and in some states your car. Otherwise, [[collision]] and your health insurance may pay.', policies: ['auto'], tags: ['accident', 'hit and run'] },
  { id: 'friend-borrows', area: 'Car', q: 'A friend borrows my car and crashes.', v: 'yes', short: 'Usually yes: insurance follows the car.', a: 'Your policy generally covers people driving with your permission. It pays first, and the claim can raise your premium. Regular drivers in your household need to be listed.', policies: ['auto'], tags: ['borrow', 'driver'] },
  { id: 'stolen-from-car', area: 'Car', q: 'My bag is stolen from my car.', v: 'yes', short: 'Your home or renters policy covers it, not car insurance.', a: 'Belongings are covered by home or renters insurance wherever they are. Damage to the car, like a broken window, goes to [[comprehensive]].', policies: ['renters', 'home', 'auto'], tags: ['theft', 'break-in'] },
  { id: 'car-flooded', area: 'Car', q: 'My car is flooded in a storm.', v: 'yes', short: 'Comprehensive covers flood damage to cars.', a: 'Flood insurance doesn\'t cover cars, but [[comprehensive]] on your auto policy does.', policies: ['auto'], tags: ['water', 'storm', 'flood'] },
  { id: 'rideshare', area: 'Car', q: 'I crash while driving for a delivery or rideshare app.', v: 'depends', short: 'Personal policies usually exclude it.', a: 'The app company\'s insurance covers some periods of a trip. A rideshare endorsement on your policy fills the gap.', policies: ['auto'], tags: ['uber', 'lyft', 'doordash', 'gig'] },

  // Travel
  { id: 'sick-before-trip', area: 'Travel', q: 'I get sick before my trip and can\'t go.', v: 'yes', short: 'Covered by trip cancellation, with a doctor\'s note.', a: 'Your own illness, or a close family member\'s, is a standard [[covered-reason]]. Conditions you already had may be excluded unless you got a [[pre-existing]] waiver.', policies: ['travel'], tags: ['cancel', 'illness'] },
  { id: 'flight-delayed', label: 'Flight delayed', area: 'Travel', q: 'My flight is delayed overnight.', v: 'yes', short: 'Travel delay pays meals and a hotel after a waiting period.', a: 'Usually after 6 to 12 hours, up to a daily limit, for covered causes like weather or mechanical problems. Many credit cards include this if you paid with the card.', policies: ['travel'], tags: ['flight', 'airline', 'delay'] },
  { id: 'change-mind', area: 'Travel', q: 'I don\'t want to go anymore.', v: 'no', short: 'Only "cancel for any reason" covers this, partly.', a: 'Standard policies only refund cancellations for listed reasons. [[cfar|Cancel for any reason]] refunds 50 to 75% and must be bought early.', policies: ['travel'], tags: ['cancel', 'cfar'] },
  { id: 'airline-cancels', area: 'Travel', q: 'The airline cancels my flight.', v: 'depends', short: 'The airline owes you a refund; insurance may cover the rest.', a: 'On flights to, from or within the US, airlines must refund cancelled flights in cash if you don\'t accept a new flight. Travel insurance can cover other prepaid costs, like hotels, if the cause is a covered reason.', policies: ['travel'], tags: ['flight', 'refund'] },
  { id: 'lost-luggage', area: 'Travel', q: 'The airline loses my luggage.', v: 'depends', short: 'The airline pays first; insurance can top up.', a: 'Airlines owe compensation up to a set limit. Travel insurance pays for essentials while a bag is delayed and can cover losses above what the airline pays, often with caps on electronics and jewelry.', policies: ['travel'], tags: ['baggage', 'bag', 'airline'] },
  { id: 'hospital-abroad', area: 'Travel', q: 'I end up in hospital abroad.', v: 'depends', short: 'Travel medical covers it; your US health plan may not.', a: 'Many US health plans pay little outside the US, and Medicare usually pays nothing. Travel medical insurance covers emergency care and evacuation up to its limits.', policies: ['travel', 'health'], tags: ['medical', 'illness', 'injury', 'abroad'] },

  // Health
  { id: 'er-out-of-network', area: 'Health', q: 'I go to an emergency room outside my network.', v: 'yes', short: 'Emergencies are covered at in-network prices.', a: 'Plans must cover emergency care at in-network cost-sharing, and federal law protects you from most surprise out-of-network bills for emergencies.', policies: ['health'], tags: ['emergency', 'network', 'hospital', 'surprise bill'] },
  { id: 'specialist-hmo', area: 'Health', q: 'I see a specialist without a referral on an HMO.', v: 'no', short: 'HMOs usually require a referral first.', a: 'Without a referral from your primary care doctor, an [[hmo|HMO]] may deny the claim. PPOs don\'t require referrals.', policies: ['health'], tags: ['doctor', 'referral'] },
  { id: 'preexisting-health', area: 'Health', q: 'I have a condition I was treated for before I came to the US.', v: 'yes', short: 'ACA health plans can\'t exclude it.', a: 'Marketplace and employer plans can\'t refuse you or charge more because of a pre-existing condition. Short-term and travel medical plans can.', policies: ['health', 'travel'], tags: ['pre-existing', 'expat', 'chronic'] },
  { id: 'dental', area: 'Health', q: 'I need a filling.', v: 'no', short: 'Adult dental care needs a separate dental plan.', a: 'Most medical plans don\'t include adult dental care. Dental plans usually cover fillings partly.', policies: ['health'], tags: ['dentist', 'teeth'] },

  // Business
  { id: 'customer-slips', label: 'Customer slipped', area: 'Business', q: 'A customer slips in my shop.', v: 'yes', short: 'General liability covers customer injuries.', a: 'The customer\'s medical bills and any claim, plus your defense, are covered by general liability or the liability part of a BOP.', policies: ['general-liability', 'bop'], tags: ['injury', 'slip and fall', 'customer'] },
  { id: 'employee-hurt', area: 'Business', q: 'An employee gets hurt at work.', v: 'yes', short: 'Workers\' comp covers it, not general liability.', a: 'Workers\' compensation pays medical bills and part of lost wages, regardless of fault. General liability excludes employee injuries.', policies: ['workers-comp'], tags: ['employee', 'injury', 'workplace'] },
  { id: 'bad-advice', area: 'Business', q: 'A client says my advice cost them money.', v: 'depends', short: 'Professional liability covers this; general liability doesn\'t.', a: 'Financial harm from your work or advice is covered by [professional liability](/business/professional-liability/) (E&O). General liability only covers physical injury and property damage.', policies: ['professional-liability'], tags: ['consultant', 'mistake', 'negligence'] },
  { id: 'phishing', area: 'Business', q: 'We wired money to a scammer after a fake invoice.', v: 'depends', short: 'Only with social engineering fraud coverage.', a: 'Many cyber and crime policies exclude voluntary transfers unless you added social engineering coverage, often with a low limit.', policies: ['cyber'], tags: ['fraud', 'email', 'wire'] },
  { id: 'closure-no-damage', area: 'Business', q: 'We had to close by government order, with no damage.', v: 'no', short: 'Business income needs physical damage.', a: 'Business income coverage is triggered by direct physical loss to property. Closures without damage, such as most pandemic closures, weren\'t covered.', policies: ['business-income'], tags: ['closure', 'pandemic', 'interruption'] },
  { id: 'tools-stolen', area: 'Business', q: 'My tools are stolen from my work van.', v: 'depends', short: 'Covered by an equipment (inland marine) policy.', a: 'Commercial auto covers the van, not what\'s in it. A contractor\'s equipment policy covers the tools, often only if the van was locked.', policies: ['inland-marine', 'commercial-auto'], tags: ['theft', 'contractor', 'equipment'] },
];
